### ISSUE TITLE
Cannot save MP3 tag

### ISSUE THREAD

**Issue by ngc7293** [puddletag/puddletag#385]
Puddletag crashes when saving album art for MP3s. Still works for FLAC.

I can see this traceback in the terminal:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddleobjects.py", line 2276, in run
    self.retval = self.command()
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddleobjects.py", line 864, in threadfunc
    temp = f.next()
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddletag.py", line 742, in func
    update = setRowData(row, f, undo=True)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/tagmodel.py", line 1083, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/util.py", line 298, in write
    audio.save()
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/id3.py", line 995, in save
    audio.tags.save(v1=v1, v2=4)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/_compatid3.py", line 82, in save
    framedata = [self.__save_frame(frame, v2) for (key, frame) in frames]
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/_compatid3.py", line 145, in __save_frame
    if len(str(frame)) == 0: return ''
  File "/usr/lib/python2.7/dist-packages/mutagen/id3/_frames.py", line 498, in __bytes__
    return text_type(self).encode('utf-8')
  File "/usr/lib/python2.7/dist-packages/mutagen/id3/_frames.py", line 501, in __str__
    return u','.join([stamp.text for stamp in self.text])
AttributeError: 'unicode' object has no attribute 'text'
```

**Comment by ngc7293** [comment]
After more testing I found that the error seems to occur not because of album art, but because my 'Year' field having multiple values ( '2011\\2011' )

**Comment by sandrotosi** [comment]
according to https://en.wikipedia.org/wiki/ID3#ID3v1_and_ID3v1.1[5] the year field is 4 chars long, so `2011\2011` is an invalid value; i tried to replicate this with the newest versoin 2.0.1 and puddletag doesnt crash anymore; closing
