### ISSUE TITLE
Error when writing to network shares.

### ISSUE THREAD

**Issue by cactusharp** [puddletag/puddletag#394]
An error occured while writing to my qnap smb share.
I have run from terminal and captured the following:

puddletag Version: 1.2.0
Locale: en_AU

(python:18320): Gtk-WARNING **: Theme file for DMZ-White has no directories

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddleobjects.py", line 2276, in run
    self.retval = self.command()
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddleobjects.py", line 864, in threadfunc
    temp = f.next()
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddletag.py", line 742, in func
    update = setRowData(row, f, undo=True)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/tagmodel.py", line 1083, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/util.py", line 298, in write
    audio.save()
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/vorbis.py", line 224, in save
    audio.save()
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 158, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 128, in wrapper
    writable, create) as h:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 227, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 95] Operation not supported: '/run/user/1000/gvfs/smb-share:server=callisto.local,share=dataw/Public/Audio/Flac/Eskimo Joe/2001 - Girl/02 - Wake Up.flac'

network permissions are ok, have tried same share mounted with nfs instead of smb and have no issue - believe it might be a path string problem.

Related to closed issue #110 also i think..

Ta

**Comment by sandrotosi** [comment]
`Errno 95` is a [linux error](https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_node/libc_17.html#IDX107), so it's the backend that's failing not puddletab; closing
