### ISSUE TITLE
Cannot start puddletag 1.2.0-1 anymore after update of 30/12/18

### ISSUE THREAD

**Issue by tnuk** [puddletag/puddletag#422]
Hi, from one day to the next I can't start/open puddletag anymore (the best mp3 tagging software of them all). Using Ubuntu 18.10. When I enter 'puddletag &' in the shell the error message is:

puddletag Version: 1.2.0
Locale: en_GB
Object::disconnect: Unexpected null parameter
Traceback (most recent call last):
  File "/usr/local/bin/puddletag", line 350, in <module>
    win = MainWin()
  File "/usr/local/lib/python2.7/dist-packages/puddlestuff/puddletag.py", line 370, in __init__
    self.restoreSettings()
  File "/usr/local/lib/python2.7/dist-packages/puddlestuff/puddletag.py", line 637, in restoreSettings
    status['genres'] = genres.load_genres()
  File "/usr/local/lib/python2.7/dist-packages/puddlestuff/genres.py", line 15, in load_genres
    open(filepath, 'r').readlines()]
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 3: invalid start byte

On the Ubuntu Software Center it says the last update was 30/12/18 which would make sense because the problem started today. I am not sure though if this could mean the date of uninstalling and re-installing the software because I tried this already.

Any solution? Any workaround? I tried alternative apps but none comes close.
Please help. Using it every day..
Thanks!!

**Comment by milkmiruku** [comment]
Arch based users need to install `python2-sip-pyqt4` to resolve.

**Comment by steveduell** [comment]
That did the trick.  Thanks a million!
