### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by ruanom** [puddletag/puddletag#447]
All of a sudden, puddletag has stopped uploading music folder and I get the following:

/srv/dev-disk-by-label-HG/HGtop/MUSIC/Artists/America/1994 - Hourglass/04 - Mirror to Mirror.flac
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/puddlestuff/puddleobjects.py", line 675, in gettag
    return audioinfo.Tag(f)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/tagmodel.py", line 298, in ReplacementTag
    return extensions[ext][1](filename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/tagmodel.py", line 151, in __init__
    super(ModelTag, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/vorbis.py", line 74, in __init__
    util.MockTag.__init__(self, filename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/util.py", line 663, in __init__
    self.link(filename)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/vorbis.py", line 171, in link
    tags, audio = self.load(filename, base)
  File "/usr/lib/python2.7/dist-packages/puddlestuff/audioinfo/util.py", line 763, in load
    audio = filetype(filename)
  File "/usr/lib/python2.7/dist-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 152, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 123, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/flac.py", line 790, in load
    while self.__read_metadata_block(fileobj):
  File "/usr/lib/python2.7/dist-packages/mutagen/flac.py", line 728, in __read_metadata_block
    block = block_type(data)
  File "/usr/lib/python2.7/dist-packages/mutagen/flac.py", line 109, in __init__
    self.load(data)
  File "/usr/lib/python2.7/dist-packages/mutagen/flac.py", line 210, in load
    self.min_blocksize = int(to_int_be(data.read(2)))
  File "/usr/lib/python2.7/dist-packages/mutagen/flac.py", line 70, in read
    size, len(data)))

Any advice, please?

**Comment by sandrotosi** [comment]
please upgrade to 2.0.1 which contains the ports to python3 and pyqt5
