### ISSUE TITLE
error with autonumbering function

### ISSUE THREAD

**Issue by sandrotosi** [puddletag/puddletag#482]
<a href="https://github.com/ghost"><img src="https://avatars3.githubusercontent.com/u/10137?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ghost](https://github.com/ghost)**
_Thu May 21 12:37:17 2020_
_Originally opened as https://github.com/sandrotosi/puddletag/issues/3_

----

```
puddletag Version: 2.0.0
Locale: it_IT
Traceback (most recent call last):
  File "/home/utonto/Scaricati/source/puddlestuff/puddleobjects.py", line 2325, in run
    self.retval = self.command()
  File "/home/utonto/Scaricati/source/puddlestuff/puddleobjects.py", line 870, in threadfunc
    temp = next(f)
  File "/home/utonto/Scaricati/source/puddlestuff/puddletag.py", line 750, in func
    for row, f in izip(rows, tagiter):
  File "/home/utonto/Scaricati/source/puddlestuff/mainwin/funcs.py", line 419, in tagiter
    val = function(rowtags.get(field, u''), rowtags, state, r_tags=f)
  File "/home/utonto/Scaricati/source/puddlestuff/findfunc.py", line 851, in runFunction
    return func(**topass)
  File "/home/utonto/Scaricati/source/puddlestuff/functions.py", line 102, in autonumbering
    tracknum = state['autonumbering'][index]
KeyError: 2
```

**Comment by hboetes** [comment]
Ah! I'm not the only one!
