### ISSUE TITLE
tag source: An unhandled error occurred: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by sandrotosi** [puddletag/puddletag#523]
<a href="https://github.com/audiomuze"><img src="https://avatars0.githubusercontent.com/u/6852511?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [audiomuze](https://github.com/audiomuze)**
_Tue Jun 30 17:59:15 2020_
_Originally opened as https://github.com/sandrotosi/puddletag/issues/50_

----

```
 export QT_QPA_PLATFORMTHEME=qt5ct && /home/x/github/pt3/puddletag/source/puddletag .
puddletag Version: 2.0.0
Locale: en_US
Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/webdb.py", line 867, in search
    return tag_source_search(self.curSource, group, files)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/webdb.py", line 558, in tag_source_search
    albums = ts.search(primary, group[primary])
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/amg.py", line 616, in search
    search_results = parse_searchpage(searchpage, artist, album)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/amg.py", line 363, in parse_searchpage
    page = get_encoding(page, True, 'utf8')[1]
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/__init__.py", line 58, in get_encoding
    match = re.search('<\?xml(.+)\?>', page)
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

```

**Comment by SR-G** [comment]
Still same error here : 

```
puddletag Version: 2.0.1
Locale: C
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/puddlestuff/mainwin/funcs.py", line 198, in extended_tags
    win = helperwin.ExTags(files=status['selectedfiles'], parent=parent)
  File "/usr/lib/python3.10/site-packages/puddlestuff/helperwin.py", line 718, in __init__
    self.loadFiles(files)
  File "/usr/lib/python3.10/site-packages/puddlestuff/helperwin.py", line 918, in loadFiles
    self._settag(row, field, values, multi=True)
  File "/usr/lib/python3.10/site-packages/puddlestuff/helperwin.py", line 1100, in _settag
    valitem = StatusWidgetCombo(value, status, self._colors, preview)
  File "/usr/lib/python3.10/site-packages/puddlestuff/helperwin.py", line 520, in __init__
    items = sorted(items, key=natsort_case_key)
  File "/usr/lib/python3.10/site-packages/puddlestuff/puddleobjects.py", line 628, in natsort_case_key
    return [convert(c) for c in re.split('([0-9]+)', s)]
  File "/usr/lib/python3.10/re.py", line 230, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object
zsh: abort (core dumped)  puddletag

```

**Comment by sandrotosi** [comment]
the 2 errors are completely different. @SR-G what you're looking for is #646

**Comment by SR-G** [comment]
Maybe - the TypeError is the same (so it could have been a global problem / global solution), but indeed, the whole stacktrace / chain of calls is different - but just as an extra detail : in my case it's not AIFF at all (like in #646), just regular tags with regular .mp3 files.

**Comment by sandrotosi** [comment]
please follow up on #646 , where these additional details may help in its resolution
