### ISSUE TITLE
Random crashes evrywhere

### ISSUE THREAD

**Issue by mistersister** [puddletag/puddletag#541]
Hi, 

I noticed puddletag crashes randomly whenever I try to apply functions or quick actions. 

I was able to capture this error running the application directly from the terminal when trying to apply some renaming functions, mainly case conversion.

```
~>$ puddletag
puddletag Version: 2.0.1
Locale: en_US
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/usr/lib/python3.8/site-packages/puddlestuff/puddleobjects.py", line 895, in threadfunc
    temp = next(f)
  File "/usr/lib/python3.8/site-packages/puddlestuff/puddletag.py", line 740, in func
    update = setRowData(row, f, undo=True)
  File "/usr/lib/python3.8/site-packages/puddlestuff/tagmodel.py", line 1102, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
  File "/usr/lib/python3.8/site-packages/puddlestuff/util.py", line 318, in write
    audio.update(user_only)
  File "/usr/lib/python3.8/site-packages/puddlestuff/tagmodel.py", line 288, in update
    super(ModelTag, self).update(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/puddlestuff/audioinfo/util.py", line 867, in update
    self[key] = value
  File "/usr/lib/python3.8/site-packages/puddlestuff/tagmodel.py", line 268, in __setitem__
    super(ModelTag, self).__setitem__(key, value)
  File "/usr/lib/python3.8/site-packages/puddlestuff/audioinfo/util.py", line 476, in f
    return func(self, key, value)
  File "/usr/lib/python3.8/site-packages/puddlestuff/audioinfo/id3.py", line 968, in __setitem__
    self.__tags[key].set_value(value)
  File "/usr/lib/python3.8/site-packages/puddlestuff/audioinfo/id3.py", line 96, in <lambda>
    return lambda value: func(frame, value)
  File "/usr/lib/python3.8/site-packages/puddlestuff/audioinfo/id3.py", line 649, in set_uslt
    frames.append(id3.USLT(encoding, lang, desc, text))
  File "/usr/lib/python3.8/site-packages/mutagen/id3/_frames.py", line 63, in __init__
    setattr(self, checker.name, val)
  File "/usr/lib/python3.8/site-packages/mutagen/id3/_frames.py", line 76, in __setattr__
    self._setattr(name, checker.validate(self, value))
  File "/usr/lib/python3.8/site-packages/mutagen/id3/_specs.py", line 304, in validate
    raise TypeError("%s has to be str" % self.name)
TypeError: lang has to be str
Aborted (core dumped)
```

Im using Puddletag 2.0.1 on Arch, installed through the AUR, but same issues apply from the release downloaded from this very repo.

**Comment by sandrotosi** [comment]
@mistersister would you be able to make a complete list of all the functions/quick actions that make puddletag crash for you? thanks!

**Comment by mistersister** [comment]
> @mistersister would you be able to make a complete list of all the functions/quick actions that make puddletag crash for you? thanks!

I'm out for the weekend but will do on Monday when I return home.  Do you need the specific configuration of each action/function or just a list of the things that made the app crash? If its the latter these are the things that ended up with a crash:

Actions for case converting
Autonumbering function
Tag to Filename

**Comment by mistersister** [comment]
This is the specific config of the action that causes the program tom crash. Nothing fancy I think.

```
{
  "info": {
    "name": "case conversion"
  },
  "Func0": {
    "fields": [
      "__all"
    ],
    "func_name": "titleCase",
    "module": "puddlestuff.functions",
    "arguments": [
      "Mixed Case",
      "., !({[~/-"
    ]
  },
  "Func1": {
    "fields": [
      "__filename"
    ],
    "func_name": "titleCase",
    "module": "puddlestuff.functions",
    "arguments": [
      "lower case",
      "., !"
    ]
  }
}
```

A thing to note is that after crashing the application several times trying to work on a certain set of files, I tried with other files and it seemed to work just fine. Could it be related to my own files being somehow corrupted or having some kind of weird encoding?

**Comment by tukusejssirs** [comment]
I have encountered similar error, while I tried puddletag first time ever in my life. I just cloned the repo on Fedora 32 x86_64, installed the dependencies, modified some tags in some files (the GUI reported that I have modified 132 files), no actions, just minor modifications of the settings (like filename format). The error happened when I wrote the tags to files, at 131st file (i.e. last but one). The terminal log is below (main error: `TypeError: data has to be bytes`).

Note that I use SwayWM if that matters in tabbed mode (modal windows only are in floating mode).

<details>
   <summary>Dependencies on Fedora 32</summary>

```bash
sudo dnf -y install python3 python3-mutagen python3-pyparsing python3-pip python3-configobj python3-acoustid chromaprint-tools
sudo pip3 install pyqt5
```
</details>

<details>
   <summary>Terminal log</summary>

```bash
$ PYTHONPATH=source/ ./source/puddletag
puddletag Version: 2.0.1, Changeset: 2ee6139ce75fcac959968143023ce0b9d1d2e13f
Locale: en_GB
inotify_add_watch(/home/ts/dls/win_8_emb_std) failed: (No space left on device)
inotify_add_watch(/home/ts/dls/win_8_emb_std) failed: (No space left on device)
inotify_add_watch(/home/ts) failed: (No space left on device)
inotify_add_watch(/home) failed: (No space left on device)
inotify_add_watch(/home/ts/snd) failed: (No space left on device)
inotify_add_watch(/home/ts/snd/ustd) failed: (No space left on device)
qt.qpa.wayland: Setting cursor position is not possible on wayland
qt.qpa.wayland: Setting cursor position is not possible on wayland
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
qt.qpa.wayland: setGrabPopup called with a parent, QtWaylandClient::QWaylandXdgSurface(0x562987262ee0) which does not match the current topmost grabbing popup, QtWaylandClient::QWaylandXdgSurface(0x5629874645d0) According to the xdg-shell protocol, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly because xdg-shell mandate that child popups close before parents
qt.qpa.wayland: setGrabPopup called with a parent, QtWaylandClient::QWaylandXdgSurface(0x562987262ee0) which does not match the current topmost grabbing popup, QtWaylandClient::QWaylandXdgSurface(0x56298728e7e0) According to the xdg-shell protocol, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly because xdg-shell mandate that child popups close before parents
qt.qpa.wayland: setGrabPopup called with a parent, QtWaylandClient::QWaylandXdgSurface(0x562987262ee0) which does not match the current topmost grabbing popup, QtWaylandClient::QWaylandXdgSurface(0x562987ac4150) According to the xdg-shell protocol, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly because xdg-shell mandate that child popups close before parents
qt.qpa.wayland: setGrabPopup called with a parent, QtWaylandClient::QWaylandXdgSurface(0x562987262ee0) which does not match the current topmost grabbing popup, QtWaylandClient::QWaylandXdgSurface(0x5629877a18f0) According to the xdg-shell protocol, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly because xdg-shell mandate that child popups close before parents
Traceback (most recent call last):
  File "/git/others/puddletag/source/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/git/others/puddletag/source/puddlestuff/puddleobjects.py", line 895, in threadfunc
    temp = next(f)
  File "/git/others/puddletag/source/puddlestuff/puddletag.py", line 740, in func
    update = setRowData(row, f, undo=True)
  File "/git/others/puddletag/source/puddlestuff/tagmodel.py", line 1102, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
  File "/git/others/puddletag/source/puddlestuff/util.py", line 318, in write
    audio.update(user_only)
  File "/git/others/puddletag/source/puddlestuff/tagmodel.py", line 288, in update
    super(ModelTag, self).update(*args, **kwargs)
  File "/git/others/puddletag/source/puddlestuff/audioinfo/util.py", line 867, in update
    self[key] = value
  File "/git/others/puddletag/source/puddlestuff/tagmodel.py", line 268, in __setitem__
    super(ModelTag, self).__setitem__(key, value)
  File "/git/others/puddletag/source/puddlestuff/audioinfo/util.py", line 473, in f
    return func(self, mapping[key], value)
  File "/git/others/puddletag/source/puddlestuff/audioinfo/id3.py", line 980, in __setitem__
    self.__tags.update(create_ufid(key, value))
  File "/git/others/puddletag/source/puddlestuff/audioinfo/id3.py", line 528, in create_ufid
    frame = id3.UFID(owner, value)
  File "/usr/lib/python3.8/site-packages/mutagen/id3/_frames.py", line 65, in __init__
    setattr(self, checker.name, val)
  File "/usr/lib/python3.8/site-packages/mutagen/id3/_frames.py", line 78, in __setattr__
    self._setattr(name, checker.validate(self, value))
  File "/usr/lib/python3.8/site-packages/mutagen/id3/_specs.py", line 436, in validate
    raise TypeError("%s has to be bytes" % self.name)
TypeError: data has to be bytes
```
</details>

**Comment by blueblots** [comment]
@mistersister did any of the crashes you experienced happen in
circumstances like those described in 
https://github.com/puddletag/puddletag/pull/550 or 
https://github.com/puddletag/puddletag/pull/551?

**Comment by mistersister** [comment]
No, I double-checked both and none of them are the case. Specially not #551 

In my case, seems to be when clicking the Actions (not the Quick Actions) button on the main window toolbar. There, I have the two default actions for Standard and Case conversion plus a custom Case conversion that better suits my needs.

The strange thing is that this not always crashes the program. When I load certain folders it crashes, while with others seems to work just fine. 

I got this crash with one such folder. Not sure if it will be of any help for you but here it is:

```
$ puddletag
puddletag Version: 2.0.1
Locale: en_US
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/puddlestuff/mainwin/funcs.py", line 401, in run_action
    win = actiondlg.ActionWindow(parent, example)
  File "/usr/lib/python3.8/site-packages/puddlestuff/actiondlg.py", line 778, in __init__
    self.updateExample()
  File "/usr/lib/python3.8/site-packages/puddlestuff/actiondlg.py", line 932, in updateExample
    tags = apply_macros(macros, self.example, state,
  File "/usr/lib/python3.8/site-packages/puddlestuff/findfunc.py", line 658, in apply_macros
    return apply_actions(actions, audio, state)
  File "/usr/lib/python3.8/site-packages/puddlestuff/findfunc.py", line 623, in apply_actions
    temp = func.runFunction(val, audio, state, None, r_tags)
  File "/usr/lib/python3.8/site-packages/puddlestuff/findfunc.py", line 890, in runFunction
    ret.append(func(**topass))
  File "/usr/lib/python3.8/site-packages/puddlestuff/functions.py", line 683, in replace
    match = pat.search(text, start)
TypeError: cannot use a string pattern on a bytes-like object
Aborted (core dumped)
```

**Comment by ritze** [comment]
I have similar problems since a half year.

It seems that puddletag crashes with certain files (always the same files).

**Comment by CiCCkany** [comment]
Hi,

I have a very similar issue (maybe the same).
Whenever I try to write the tags which were retrieved from MusicBrainz, puddletag crashes.

**puddltag version:** 2.0.1
**Linux distribution:** Arch (current version, but I noticed the issue several months ago)
**file type have the issue:** MP3
**file type doesn't have to issue:** FLAC
**Python version:** 3.9.4

**Steps to reproduce:**

1. Start puddletag
2. Open directory containing MP3 files of a single album
3. Select files
4. Select MusicBrainz from the Tag Sources drop-down menu
5. Enter something relevant into the Search field if needed
6. Click Search
7. Select the correct album from the search hit list
8. Click Write
9. puddletag crashes

Stack trace:
```
$ puddletag 
puddletag Version: 2.0.1
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Locale: en_US
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/usr/lib/python3.9/site-packages/puddlestuff/puddleobjects.py", line 895, in threadfunc
    temp = next(f)
  File "/usr/lib/python3.9/site-packages/puddlestuff/puddletag.py", line 740, in func
    update = setRowData(row, f, undo=True)
  File "/usr/lib/python3.9/site-packages/puddlestuff/tagmodel.py", line 1102, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
  File "/usr/lib/python3.9/site-packages/puddlestuff/util.py", line 318, in write
    audio.update(user_only)
  File "/usr/lib/python3.9/site-packages/puddlestuff/tagmodel.py", line 288, in update
    super(ModelTag, self).update(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/puddlestuff/audioinfo/util.py", line 867, in update
    self[key] = value
  File "/usr/lib/python3.9/site-packages/puddlestuff/tagmodel.py", line 268, in __setitem__
    super(ModelTag, self).__setitem__(key, value)
  File "/usr/lib/python3.9/site-packages/puddlestuff/audioinfo/util.py", line 473, in f
    return func(self, mapping[key], value)
  File "/usr/lib/python3.9/site-packages/puddlestuff/audioinfo/id3.py", line 980, in __setitem__
    self.__tags.update(create_ufid(key, value))
  File "/usr/lib/python3.9/site-packages/puddlestuff/audioinfo/id3.py", line 528, in create_ufid
    frame = id3.UFID(owner, value)
  File "/usr/lib/python3.9/site-packages/mutagen/id3/_frames.py", line 63, in __init__
    setattr(self, checker.name, val)
  File "/usr/lib/python3.9/site-packages/mutagen/id3/_frames.py", line 76, in __setattr__
    self._setattr(name, checker.validate(self, value))
  File "/usr/lib/python3.9/site-packages/mutagen/id3/_specs.py", line 430, in validate
    raise TypeError("%s has to be bytes" % self.name)
TypeError: data has to be bytes
Aborted (core dumped)

```

**Comment by angelu5** [comment]
good day all

i found puddletag and i have tried many other tagging programs and they dont come close to puddletag , i really want to use puddletag but i have the same issue as everyone above.

i tried the puddletag-git and the normal puddletag AUR both do the same thing.

1. open puddletag
2. select music folder
3. select mp3 files
4. lookup
5. select choice
6. click to write
7. and then crash

output from terminal

$ puddletag
puddletag Version: 2.0.1
Locale: en_ZA
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/usr/lib/python3.9/site-packages/puddlestuff/puddleobjects.py", line 895, in threadfunc
    temp = next(f)
  File "/usr/lib/python3.9/site-packages/puddlestuff/puddletag.py", line 740, in func
    update = setRowData(row, f, undo=True)
  File "/usr/lib/python3.9/site-packages/puddlestuff/tagmodel.py", line 1102, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
  File "/usr/lib/python3.9/site-packages/puddlestuff/util.py", line 318, in write
    audio.update(user_only)
  File "/usr/lib/python3.9/site-packages/puddlestuff/tagmodel.py", line 288, in update
    super(ModelTag, self).update(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/puddlestuff/audioinfo/util.py", line 867, in update
    self[key] = value
  File "/usr/lib/python3.9/site-packages/puddlestuff/tagmodel.py", line 268, in __setitem__
    super(ModelTag, self).__setitem__(key, value)
  File "/usr/lib/python3.9/site-packages/puddlestuff/audioinfo/util.py", line 473, in f
    return func(self, mapping[key], value)
  File "/usr/lib/python3.9/site-packages/puddlestuff/audioinfo/id3.py", line 968, in __setitem__
    self.__tags[key].set_value(value)
  File "/usr/lib/python3.9/site-packages/puddlestuff/audioinfo/id3.py", line 96, in <lambda>
    return lambda value: func(frame, value)
  File "/usr/lib/python3.9/site-packages/puddlestuff/audioinfo/id3.py", line 540, in set_ufid
    frame.data = value
  File "/usr/lib/python3.9/site-packages/mutagen/id3/_frames.py", line 76, in __setattr__
    self._setattr(name, checker.validate(self, value))
  File "/usr/lib/python3.9/site-packages/mutagen/id3/_specs.py", line 430, in validate
    raise TypeError("%s has to be bytes" % self.name)
TypeError: data has to be bytes
Aborted (core dumped)

**Comment by corubba** [comment]
Starting from the top, [the error @mistersister originally reported](https://github.com/puddletag/puddletag/issues/541#issue-713434800): From the traceback I can tell that it happened when writing a ID3 USLT frame (unsychronized lyrics). These always contain the language that the lyrics are in, and that had apparently some unexpected format. It wasn't directly related to the action/function he called, but rather the tag writing it triggered. I tried various way to replicate the error but was unable to, so I believe it's already fixed. Feel free to prove me wrong with an example file. :wink:

Next up is the [second error from @mistersister](https://github.com/puddletag/puddletag/issues/541#issuecomment-717111801), which is a very vague one. All the traceback tells me that it encountered a binary tag content when trying to apply a "replace" function/action. This usually points to some bug in the wrappers that handle the conversions between puddletag's internal model and the file-type-specific formats (like ID3 or Vorbis). But without a samplefile to analyse (or at least more info) this is practically unsolvable.

Last but not least the error from [CiCCkany](https://github.com/puddletag/puddletag/issues/541#issuecomment-832455369), [benreese0](https://github.com/puddletag/puddletag/issues/541#issuecomment-839209871) and [angelu5](https://github.com/puddletag/puddletag/issues/541#issuecomment-855832522): All of them point to the same issue with ID3's UFID frame that was recently fixed with #693, so I proclaim them as fixed. This probably also holds true for the report from [ritze](https://github.com/puddletag/puddletag/issues/541#issuecomment-758015288) since it also only affected mp3's (which use ID3), but hard to tell without more infos.

**Comment by benreese0** [comment]
Thank you @corubba !

**Comment by CiCCkany** [comment]
Great! Thank you @corubba !

**Comment by mistersister** [comment]
Hello, extremely late I know, but for instance @corubba, here is a mp3 file that is making v2.1.1 to crash when writing any tag. Packaged in a gz file github does not allow mp3.

[test_file.tar.gz](https://github.com/puddletag/puddletag/files/8753129/test_file.tar.gz)
(
