### ISSUE TITLE
APE tags issue

### ISSUE THREAD

**Issue by samuraibrian** [puddletag/puddletag#553]
This is happening with v1.2.0, and v2.0.1 on Ubuntu 18.04. I have a bunch of MP3 files with an ID3v1.0 tag, and an APEv2 tag - exiftool, and hexdump confirm that. Puddletag successfully deletes the ID3v1.0 tag, but not the APEv2 tag. E.g.:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/puddlestuff/mainwin/tagtools.py", line 36, in _remove_tag
    _delete[tag](f.filepath)
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 148, in wrapper_func
    return func(h, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/apev2.py", line 511, in delete
    t = APEv2(filething)
  File "/usr/lib/python2.7/dist-packages/mutagen/apev2.py", line 244, in __init__
    super(_CIDictProxy, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/_tags.py", line 111, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/apev2.py", line 297, in load
    self.__parse_tag(data.tag, data.items)
  File "/usr/lib/python2.7/dist-packages/mutagen/apev2.py", line 342, in __parse_tag
    value = _get_value_type(kind)._new(value)
  File "/usr/lib/python2.7/dist-packages/mutagen/apev2.py", line 559, in _new
    instance._parse(data)
  File "/usr/lib/python2.7/dist-packages/mutagen/apev2.py", line 589, in _parse
    reraise(APEBadItemError, e, sys.exc_info()[2])
  File "/usr/lib/python2.7/dist-packages/mutagen/apev2.py", line 587, in _parse
    self.value = data.decode("utf-8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
APEBadItemError: 'utf8' codec can't decode byte 0xb2 in position 0: invalid start byte
```
The "APEBadItemError" error is similar in every MP3 - referring to the byte that is either immediately after, or 2 bytes after, the null separator in an Ape tag (Key) XLastScheduled (in this particular example, 0xb2):

```
005fc660  32 32 31 48 00 00 00 00  00 00 02 58 4c 61 73 74  |221H.......XLast|
005fc670  53 63 68 65 64 75 6c 65  64 00 b2 92 50 51 bc 32  |Scheduled...PQ.2|
005fc680  38 51 7c 38 25 51 b8 8d  10 51 18 7d fa 50 9b 91  |8Q|8%Q...Q.}.P..|
005fc690  ee 50 ba 34 cf 50 ee 76  cb 50 f4 b9 bf 50 3a 38  |.P.4.P.v.P...P:8|
005fc6a0  b1 50 d5 ae ac 50 ef 4c  a4 50 1d 9c 9d 50 4e 5d  |.P...P.L.P...PN]|
005fc6b0  9b 50 00 00 21 00 00 00  21 00 00 00 21 00 00 00  |.P..!...!...!...|
005fc6c0  21 00 02 00 00 00 00 00  00 00 49 6e 74 72 6f 00  |!.........Intro.|

X  L  a  s  t  S  c  h  e  d  u  l  e  d     
58 4c 61 73 74 53 63 68 65 64 75 6c 65 64 00 b2 92 50 51 bc 32 38 51 7c 38 25 51 b8 8d 10 51 18 7d fa 50 9b 91 ee 50 ba 34 cf 50 ee 76 cb 50 f4 b9 bf 50 3a 38 b1 50 d5 ae ac 50 ef 4c a4 50 1d 9c 9d 50 4e 5d 9b 50 00 00 21 00 00 00 21 00 00 00 21 00 00 00 21 00 02 00 00 00 00 00 00 00

```
I'm guessing this issue really belongs on the Mutagen forums?

BR, Jon

**Comment by samuraibrian** [comment]
Hmmm. Turns out that (unconventional) APEv2 tag is added by StationPlaylist (radio station software), when it imports MP3s into it's database.
