### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object when opening Extended Tags editor

### ISSUE THREAD

**Issue by mbirth** [puddletag/puddletag#555]
```
puddletag Version: 2.0.1, Changeset: d9d397ee5e160d66366c4fcc0aa9e6be09422f1c
Locale: en_GB
qt.qpa.window: <QNSWindow: 0x7ff8e79ee5b0; contentView=<QNSView: 0x7ff8e72fb200; QCocoaWindow(0x7ff8e8964d20, window=QWidgetWindow(0x7ff8e72d3900, name="QPushButtonClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Traceback (most recent call last):
  File "/Users/mbirth/Development/puddletag/source/puddlestuff/mainwin/funcs.py", line 198, in extended_tags
    win = helperwin.ExTags(files=status['selectedfiles'], parent=parent)
  File "/Users/mbirth/Development/puddletag/source/puddlestuff/helperwin.py", line 718, in __init__
    self.loadFiles(files)
  File "/Users/mbirth/Development/puddletag/source/puddlestuff/helperwin.py", line 918, in loadFiles
    self._settag(row, field, values, multi=True)
  File "/Users/mbirth/Development/puddletag/source/puddlestuff/helperwin.py", line 1100, in _settag
    valitem = StatusWidgetCombo(value, status, self._colors, preview)
  File "/Users/mbirth/Development/puddletag/source/puddlestuff/helperwin.py", line 520, in __init__
    items = sorted(items, key=natsort_case_key)
  File "/Users/mbirth/Development/puddletag/source/puddlestuff/puddleobjects.py", line 628, in natsort_case_key
    return [convert(c) for c in re.split('([0-9]+)', s)]
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/re.py", line 231, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object
```

Happens with 2.0.1 (e0d3588) and master (d9d397e).

**Comment by mbirth** [comment]
Might be related to #556 .
