### ISSUE TITLE
TypeError: Object of type bytes is not JSON serializable when doing "Copy All Fields"

### ISSUE THREAD

**Issue by mbirth** [puddletag/puddletag#556]
This is with current master (d9d397e):

```
QCocoaWindow(0x7fd4122a14f0, window=QWidgetWindow(0x7fd4122f0210, name="QPushButtonClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7fd41229c390; contentView=<QNSView: 0x7fd4122a4b20; QCocoaWindow(0x7fd413e563c0, window=QWidgetWindow(0x7fd412ff0020, name="QPushButtonClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
qt.qpa.window: <QNSWindow: 0x7fd412581210; contentView=<QNSView: 0x7fd4144478a0; QCocoaWindow(0x7fd412c22fa0, window=QWidgetWindow(0x7fd412c22ea0, name="QPushButtonClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Traceback (most recent call last):
  File "/Users/mbirth/Development/puddletag/source/puddlestuff/mainwin/funcs.py", line 130, in copy_whole
    data = json.dumps(list(map(tag_to_json, tags)))
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by sandrotosi** [comment]
@mbirth thanks for your reports, but i'm afraid you need to provide more details than just the traceback. f.e. i just tried to replicate tihs, and it works just fine.

To make these reports actionable, please provide more details -- thanks!

**Comment by mbirth** [comment]
I just tested this with other MP3 files and it seems it's a problem with some files I've ripped from Audio CD to MP3 using [Max](https://sbooth.org/Max/). Here's some metadata (if you have a private mail address, I can send you the file):

```
ExifTool Version Number         : 11.88
File Name                       : 04 Blur - Tender.mp3
Directory                       : .
File Size                       : 16 MB
File Modification Date/Time     : 2020:11:01 20:59:49+01:00
File Access Date/Time           : 2020:11:01 23:02:21+01:00
File Inode Change Date/Time     : 2020:11:01 23:02:10+01:00
File Permissions                : rwxrw-r--
File Type                       : MP3
File Type Extension             : mp3
MIME Type                       : audio/mpeg
MPEG Audio Version              : 1
Audio Layer                     : 3
Sample Rate                     : 44100
Channel Mode                    : Joint Stereo
MS Stereo                       : On
Intensity Stereo                : Off
Copyright Flag                  : False
Original Media                  : True
Emphasis                        : None
VBR Frames                      : 17652
VBR Bytes                       : 11225117
VBR Scale                       : 75
Encoder                         : LAME3.100.�5
ID3 Size                        : 5744294
Album                           : Long Way Round: Music From the TV Series
Artist                          : Blur
Genre                           : Soundtrack
Recording Time                  : 2004
Title                           : Tender
Track                           : 4/15
Compilation                     : Yes
Part Of Set                     : 1
Length                          : 461 s
Picture MIME Type               : image/png
Picture Type                    : Other
Picture Description             :
Picture                         : (Binary data 5742459 bytes, use -b option to extract)
ISRC                            : GAQ5=9900131
User Defined Text               : (MusicBrainz Disc Id) 3B6qxzVxnS70Z9GqdV3B0HuDUsI-
Encoded By                      : LAME 3.100 (Max 25)
Encoding Time                   : 2020:11:01 17:37:30
Tagging Time                    : 2020:11:01 17:37:30
Year                            : 2004
Comment                         :
Date/Time Original              : 2004
Audio Bitrate                   : 195 kbps
Duration                        : 0:07:41 (approx)
```

I suspect the almost 6 MB cover art is what's making puddletag stumble...

**Comment by sandrotosi** [comment]
sure, you can send it to `sandro.tosi -at- g m a i l`

**Comment by sandrotosi** [comment]
I'm sorry but i'm unable to fix this bug: i've wasted several hours trying to navigate puddletag source (which is still pretty new to me) and i still cant find the root cause of this. the immediate reason the code crashed is because the fields contain `'mbrainz_track_id': [b'51ee01f6-d466-4cb6-b2de-df45900315a3']` which is encoded as a byte string, and `json` rejects it (correctly.

i dont know what part of the code produces that, which would also be the place to `str()` it
