### ISSUE TITLE
Action/Quick Action menu items fail to load

### ISSUE THREAD

**Issue by park-dub** [puddletag/puddletag#559]
Ubuntu 20.04
Selecting the Action or Quick Action menu items have no effect. Running from command line and selecting Action gives this error: 

```
puddletag Version: 2.0.1
Locale: en_US
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/puddlestuff/mainwin/funcs.py", line 401, in run_action
    win = actiondlg.ActionWindow(parent, example)
  File "/usr/lib/python3/dist-packages/puddlestuff/actiondlg.py", line 778, in __init__
    self.updateExample()
  File "/usr/lib/python3/dist-packages/puddlestuff/actiondlg.py", line 932, in updateExample
    tags = apply_macros(macros, self.example, state,
  File "/usr/lib/python3/dist-packages/puddlestuff/findfunc.py", line 658, in apply_macros
    return apply_actions(actions, audio, state)
  File "/usr/lib/python3/dist-packages/puddlestuff/findfunc.py", line 623, in apply_actions
    temp = func.runFunction(val, audio, state, None, r_tags)
  File "/usr/lib/python3/dist-packages/puddlestuff/findfunc.py", line 873, in runFunction
    return func(**topass)
  File "/usr/lib/python3/dist-packages/puddlestuff/functions.py", line 211, in formatValue
    ret = findfunc.parsefunc(p_pattern, m_tags, state=state)
  File "/usr/lib/python3/dist-packages/puddlestuff/findfunc.py", line 465, in parsefunc
    func_parsed = run_format_func(func[0], func[1:], m_audio, s_audio, state=state, extra=extra)
  File "/usr/lib/python3/dist-packages/puddlestuff/findfunc.py", line 331, in run_format_func
    message = message.arg(arglen_error(e, topass, func, False))
  File "/usr/lib/python3/dist-packages/puddlestuff/findfunc.py", line 71, in arglen_error
    raise e
  File "/usr/lib/python3/dist-packages/puddlestuff/findfunc.py", line 325, in run_format_func
    ret = func(**topass)
TypeError: replaceWithReg() missing 1 required positional argument: 'repl
```

**Comment by blueblots** [comment]
park-dub can you detail which action caused the problem, in particular
what you were trying to do and if you can remember which menu items you
clicked?

Thank you for reporting an issue.

**Comment by park-dub** [comment]
Here is a link to a screencast showing the problem. 

(url)https://www.dropbox.com/s/neqp2fey96vxzjm/Screencast%202020-11-09%2019%3A25%3A15.mp4?dl=0

**Comment by park-dub** [comment]
I notice that there are several other tickets under different names for the same issue as this one.

**Comment by sandrotosi** [comment]
> I notice that there are several other tickets under different names for the same issue as this one.

@park-dub since you've already done the work, can you mention those tickets here? i'll try to consolidate into a single issue -- thanks!
