### ISSUE TITLE
crash on invalid regex

### ISSUE THREAD

**Issue by poelzi** [puddletag/puddletag#576]
I tried regular expression replacement and had as string:
'..)' with an empty replacement.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/yqi09xbdd8mazk5jgb241187waxzyl9n-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/puddletag.py", line 773, in writeTags
    ret = self._write(tagiter, rows, previews)
  File "/nix/store/yqi09xbdd8mazk5jgb241187waxzyl9n-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/puddletag.py", line 732, in _write
    [setRowData(row, f, undo=True) for row, f in zip(rows, tagiter)]
  File "/nix/store/yqi09xbdd8mazk5jgb241187waxzyl9n-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/puddletag.py", line 732, in <listcomp>
    [setRowData(row, f, undo=True) for row, f in zip(rows, tagiter)]
  File "/nix/store/yqi09xbdd8mazk5jgb241187waxzyl9n-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/mainwin/funcs.py", line 457, in tagiter
    val = function(rowtags.get(field, ''), rowtags, state, r_tags=f)
  File "/nix/store/yqi09xbdd8mazk5jgb241187waxzyl9n-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/findfunc.py", line 873, in runFunction
    return func(**topass)
  File "/nix/store/yqi09xbdd8mazk5jgb241187waxzyl9n-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/functions.py", line 765, in replaceWithReg
    return "\\".join(replace_matches(z) for z in m_text)
  File "/nix/store/yqi09xbdd8mazk5jgb241187waxzyl9n-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/functions.py", line 765, in <genexpr>
    return "\\".join(replace_matches(z) for z in m_text)
  File "/nix/store/yqi09xbdd8mazk5jgb241187waxzyl9n-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/functions.py", line 763, in replace_matches
    raise findfunc.FuncError(str(e))
puddlestuff.findfunc.FuncError: unbalanced parenthesis at position 2
fish: “~/.nix-profile/bin/puddletag .” terminated by signal SIGABRT (Abort)
```

**Comment by sandrotosi** [comment]
I was able to replicate this error and the complete traceback is:

```
/usr/bin/python3.9 /home/morph/puddletag/source/puddletag
puddletag Version: 2.0.1, Changeset: 544455f090906ff263e9f9ca5207472e25e17770
Locale: en_US
Traceback (most recent call last):
  File "/home/morph/puddletag/source/puddlestuff/functions.py", line 748, in replace_matches
    return re.sub(regex, replace_tokens, value, 0, flags)
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 962, in parse
    raise source.error("unbalanced parenthesis")
re.error: unbalanced parenthesis at position 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/morph/puddletag/source/puddlestuff/puddletag.py", line 779, in writeTags
    s(self)
  File "/home/morph/puddletag/source/puddlestuff/puddleobjects.py", line 881, in s
    errors = next(f)
  File "/home/morph/puddletag/source/puddlestuff/puddletag.py", line 737, in func
    for row, f in zip(rows, tagiter):
  File "/home/morph/puddletag/source/puddlestuff/mainwin/funcs.py", line 456, in tagiter
    val = function(rowtags.get(field, ''), rowtags, state, r_tags=f)
  File "/home/morph/puddletag/source/puddlestuff/findfunc.py", line 870, in runFunction
    return func(**topass)
  File "/home/morph/puddletag/source/puddlestuff/functions.py", line 758, in replaceWithReg
    return "\\".join(replace_matches(z) for z in m_text)
  File "/home/morph/puddletag/source/puddlestuff/functions.py", line 758, in <genexpr>
    return "\\".join(replace_matches(z) for z in m_text)
  File "/home/morph/puddletag/source/puddlestuff/functions.py", line 756, in replace_matches
    raise findfunc.FuncError(str(e))
puddlestuff.findfunc.FuncError: unbalanced parenthesis at position 2

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

we should probably catch this error and show a popup window about it, but i dont know how to do that, so help is welcome!
