### ISSUE TITLE
Invoking Add 2 Seconds Plugin occasionally triggers core dump

### ISSUE THREAD

**Issue by audiomuze** [puddletag/puddletag#619]
Working on an NFS mounted filesystem (Arch Linux on Desktop & Arch Linux on storage server).  Invoked 'add 2 seconds to modified time' plugin and it triggered a core dump.  This does not happen every time.

`$ python /home/x/git/puddletag/source/puddletag .
puddletag Version: 2.0.1, Changeset: df5bf44a226c039e89f23df0809ddc573e911bd0
Locale: en_GB
Traceback (most recent call last):
  File "/home/x/git/puddletag/source/puddlestuff/plugins/modified_time/__init__.py", line 16, in <lambda>
    action.triggered.connect(lambda: add_seconds(parent))
  File "/home/x/git/puddletag/source/puddlestuff/plugins/modified_time/__init__.py", line 55, in add_seconds
    s(parent)
  File "/home/x/git/puddletag/source/puddlestuff/puddleobjects.py", line 881, in s
    errors = next(f)
StopIteration
Aborted (core dumped)
`

**Comment by sandrotosi** [comment]
hey @audiomuze ! can you detail how you ran the 'add 2 seconds to modified time' plugin? i cant seem to find it -- thanks!

**Comment by sandrotosi** [comment]
> hey @audiomuze ! can you detail how you ran the 'add 2 seconds to modified time' plugin? i cant seem to find it -- thanks!

nevermind, i needed to activate it first!

**Comment by sandrotosi** [comment]
Ok so digging deeper, the complete exception is:

```
Traceback (most recent call last):
  File "/home/morph/puddletag/source/puddlestuff/plugins/modified_time/__init__.py", line 43, in func
    os.utime(f.filepath, (accessed_time, time.mktime(modified_time.timetuple())))
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/morph/puddletag/source/puddlestuff/plugins/modified_time/__init__.py", line 16, in <lambda>
    action.triggered.connect(lambda: add_seconds(parent))
  File "/home/morph/puddletag/source/puddlestuff/plugins/modified_time/__init__.py", line 55, in add_seconds
    s(parent)
  File "/home/morph/puddletag/source/puddlestuff/puddleobjects.py", line 881, in s
    errors = next(f)
  File "/home/morph/puddletag/source/puddlestuff/plugins/modified_time/__init__.py", line 46, in func
    m = str(QApplication.translate("Defaults",
AttributeError: 'str' object has no attribute 'arg'

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

so the real problem here is calling `os.utime()` that returns a `Permission Error`.

This also happens if i run

```
$ touch --date='2019-01-01' /nfs/music/file.mp3
touch: setting times of '/nfs/music/file.mp3': Operation not permitted
```

this is very likely related to mount options (f.e. i have `relatime`, and `os.utime()` also tries to set the accessed time) or just how nfs works these days.

I'll try to get the error message to pop up and not puddletag to crash, but consider this plugin wont work on NFS

**Comment by audiomuze** [comment]
> I'll try to get the error message to pop up and not puddletag to crash, but consider this plugin wont work on NFS

The issue is happening with local ext4 filesystem. 
```
$ python /home/x/git/puddletag/puddletag .
puddletag Version: 2.2.0, Changeset: 4701c5dcb021505df619b8d49ac5a328df6e8594
Locale: en_US
Traceback (most recent call last):
  File "/home/x/git/puddletag/puddlestuff/plugins/modified_time/__init__.py", line 16, in <lambda>
    action.triggered.connect(lambda: add_seconds(parent))
  File "/home/x/git/puddletag/puddlestuff/plugins/modified_time/__init__.py", line 55, in add_seconds
    s(parent)
  File "/home/x/git/puddletag/puddlestuff/puddleobjects.py", line 881, in s
    errors = next(f)
StopIteration
Aborted (core dumped)
```
