### ISSUE TITLE
Right clicking on the 'Add 2 Seconds Plugin' menu item on Plugins menu triggers core dump (repeatable)

### ISSUE THREAD

**Issue by audiomuze** [puddletag/puddletag#620]
Right clicking on the 'Add 2 Seconds Plugin' menu item on Plugins menu triggers core dump (repeatable).

```
$ python /home/x/git/puddletag/source/puddletag .
puddletag Version: 2.0.1, Changeset: df5bf44a226c039e89f23df0809ddc573e911bd0
Locale: en_GB
Traceback (most recent call last):
  File "/home/x/git/puddletag/source/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/home/x/git/puddletag/source/puddlestuff/puddleobjects.py", line 893, in threadfunc
    while not win.wasCanceled:
NameError: free variable 'win' referenced before assignment in enclosing scope
Aborted (core dumped)
```

**Comment by sandrotosi** [comment]
i'm able to replicate this, just a note that for this to happen the track list needs to be empty; happens both with right or left click on the menu entry
