### ISSUE TITLE
Core dumped attempting to add an action to Export Artwork to File (repeatable)

### ISSUE THREAD

**Issue by audiomuze** [puddletag/puddletag#623]
`Traceback (most recent call last):
  File "/home/x/git/puddletag/source/puddlestuff/actiondlg.py", line 674, in addBuddy
    self.updateExample()
  File "/home/x/git/puddletag/source/puddlestuff/actiondlg.py", line 623, in updateExample
    tags = apply_actions(self.functions, self.example, state)
  File "/home/x/git/puddletag/source/puddlestuff/findfunc.py", line 620, in apply_actions
    temp = func.runFunction(val, audio, state, None, r_tags)
  File "/home/x/git/puddletag/source/puddlestuff/findfunc.py", line 870, in runFunction
    return func(**topass)
  File "/home/x/git/puddletag/source/puddlestuff/functions.py", line 897, in save_artwork
    fobj.write(data)
TypeError: write() argument must be str, not bytes
Aborted (core dumped)
`

![image](https://user-images.githubusercontent.com/6852511/130368646-c07fa281-1cf0-444e-b3d2-f0959993de04.png)
Core is dumped as soon as you select Ok

**Comment by audiomuze** [comment]
If one opens the Actions window without any files loaded in puddletag and attempts the same as above, one also gets a Core dumped, but with the following:

`puddletag Version: 2.0.1, Changeset: 885444fa8c565989dafa93e26d1851b32849bcab
Locale: en_GB
Traceback (most recent call last):
  File "/home/x/git/puddletag/source/puddlestuff/actiondlg.py", line 674, in addBuddy
    self.updateExample()
  File "/home/x/git/puddletag/source/puddlestuff/actiondlg.py", line 623, in updateExample
    tags = apply_actions(self.functions, self.example, state)
  File "/home/x/git/puddletag/source/puddlestuff/findfunc.py", line 619, in apply_actions
    val = audio.get(field, '')
AttributeError: 'NoneType' object has no attribute 'get'
Aborted (core dumped)
`

**Comment by blueblots** [comment]
Hi @audiomuze there is a pull request #551 that fixes this waiting to be merged. I will link this issue to that PR.
