### ISSUE TITLE
plugin loading error

### ISSUE THREAD

**Issue by K3nn3th2** [puddletag/puddletag#639]
hey guys,

when trying to run a custom plugin i get the following error:

```
puddletag Version: 2.0.1
Locale: en_GB
[2021-10-16 02:17:17,193]ERROR:Failed to load plugin Example Functions; error=No module named 'puddlestuff.plugins.functionplugin'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/puddlestuff/pluginloader.py", line 78, in load_plugins
    module = import_module('puddlestuff.plugins.' + plugin[MODULE_NAME])
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'puddlestuff.plugins.functionplugin'
```

the plugin has a folder named functionplugin and resides in ~/.local/share/puddletag/plugins/
it worked when i used puddletag on my old OS with python2.7

i ran 2to3 on the __init__ script thinking it might be due to an error in the script. but the script returns no errors. puddletag just gives the above mentioned error..

any ideas how to fix this? would hugely appreciate any help on this!

thanks for making puddletag so great !

**Comment by sandrotosi** [comment]
without seeing the plugin, is hard to say what's going on. I suspect, for some reason, your plugin cannot be compiled and so python returns that's no importable (because there's no bytecode available). You mentioned it used to work with python 2.7: please do note now puddletag is python3-only, so your plugin will need to be ported.

**Comment by K3nn3th2** [comment]
the same error appears trying to load the empty plugin example called functionplugin from [here](https://docs.puddletag.net/_downloads/e1f44bb1cbe1ac486c102e6670cd74d2/functionplugin.tar.gz).

i guess that one should work..?
