### ISSUE TITLE
Unable to launch PuddleTag

### ISSUE THREAD

**Issue by gitdwarf** [puddletag/puddletag#650]
When I try and start puddletag, I get the below error

I am using Python3.9.9 and all requirements have been installed

```
$ ./puddletag 
puddletag Version: 2.0.1
Locale: en_AU
Traceback (most recent call last):
  File "/home/thedwarf/Stuff/Apps/puddletag/source/./puddletag", line 333, in <module>
    from puddlestuff.puddletag import MainWin
  File "/home/thedwarf/Stuff/Apps/puddletag/source/puddlestuff/puddletag.py", line 12, in <module>
    from . import mainwin
  File "/home/thedwarf/Stuff/Apps/puddletag/source/puddlestuff/mainwin/__init__.py", line 4, in <module>
    from . import dirview
  File "/home/thedwarf/Stuff/Apps/puddletag/source/puddlestuff/mainwin/dirview.py", line 12, in <module>
    from ..tagmodel import has_previews
  File "/home/thedwarf/Stuff/Apps/puddletag/source/puddlestuff/tagmodel.py", line 31, in <module>
    from .audio_filter import parse as filter_audio
  File "/home/thedwarf/Stuff/Apps/puddletag/source/puddlestuff/audio_filter.py", line 183, in <module>
    bool_expr = operatorPrecedence(tokens, bool_exprs)
NameError: name 'operatorPrecedence' is not defined
```

**Comment by sandrotosi** [comment]
duplicate of #643
