### ISSUE TITLE
Initiating Masstagger triggers core dump

### ISSUE THREAD

**Issue by audiomuze** [puddletag/puddletag#720]
```
python /home/x/git/puddletag/puddletag .
puddletag Version: 2.1.1, Changeset: e9d16b9957cc44343f602f8efbcf8faf2143997d
Locale: en_GB
:insertStarting search for: <br />artist=<b>Bonnie Tyler</b> <br />album=<b>Diamond Cut [Expanded Edition]</b><br />
Traceback (most recent call last):
  File "/home/x/git/puddletag/puddlestuff/puddleobjects.py", line 2437, in run
    self.retval = self.command()
  File "/home/x/git/puddletag/puddlestuff/masstag/dialogs.py", line 650, in run_masstag
    masstag(mtp, files, self.__flag, search_error,
  File "/home/x/git/puddletag/puddlestuff/masstag/__init__.py", line 430, in masstag
    for matches, results, tsp in mtp.search(files, errors=mtp_error_func):
  File "/home/x/git/puddletag/puddlestuff/masstag/__init__.py", line 578, in search
    assert profiles
AssertionError
Aborted (core dumped)
```

**Comment by audiomuze** [comment]
Just wanted to say thanks for sorting this.  Puddletag is infinitely more useful with masstagging working again.
