### ISSUE TITLE
"Extended Tags" menu option does not open

### ISSUE THREAD

**Issue by dannn-o** [puddletag/puddletag#756]
### Current Behavior

When trying to open the "Extended Tags" menu option to edit one of the embedded ID3 tags for a song,
nothing happens at all.

### Expected Behavior

A secondary window should appear that has the various fields that can be edited such as
album, unsyncedlyrics, etc., along with the current value of each field and icons to assist
with editing (Add, Edit, Duplicate, etc).

### Steps To Reproduce

1. Open a folder with songs from an album.
2. Select one of the songs and then try to invoke the "Extended Tags" menu option (by either right-clicking the song and left-clicking "Extended Tags", or pressing Ctrl + E.  Both of these have been tested, as well as the menu option Edit - Extended Tags).

### Information about your system

Puddletag: 2.2.0 (run from source code, using a cloned Github library).
OS:  Linux Mint 20.3
Python: 3.8.10 and 2.7.18
PyQt: 5.14.1

### Anything else?

As a workaround, I am using an Appimage (older) version, 1.2.0, of Puddletag.  
The "Extended Tags" menu option works correctly in that version.

Also, the problem described above was happening with version 2.1.1, which
was the first source code version I had installed.  I recently updated the cloned
library to 2.2.0 (currently the latest release at Github) to confirm the problem is still happening,

**Comment by dannn-o** [comment]
Update:  After some additional work and experimentation, I discovered that version 2.2.0 does occasionally open the
"Extended Tags" window successfully.  It appears to be dependent on which / how many ID3 tags are populated in
the file when attempted.  If I open "Extended Tags" on an audio file that was just ripped (using K3B), the window
opens successfully.  After running the file through the import process using the beets app (which imports ID3 tags primarily
from Musicbrainz), the "Extended Tags" window will not open at all.

If I have time, I will try to diagnose further.  My suspicion is that the album art may be triggering the bug, or some combination of
tags if it's not album art.

**Comment by dannn-o** [comment]
Thanks for the reply.  Here is the terminal session running version 2.2.0 (from source):
```
dan@XPS-8940:~/puddletag$ ./puddletag
puddletag Version: 2.2.0, Changeset: ff36a9bc8ebc971e9bfc5e6aa692eef310122100
qt5ct: using qt5ct plugin
Locale: en_US
qt5ct: D-Bus global menu: no
Traceback (most recent call last):
  File "/home/dan/puddletag/puddlestuff/mainwin/artwork.py", line 108, in fill
    self.picwidget.setImages(pics, default=2)
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 2044, in setImages
    self.currentImage = default
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 1953, in _setCurrentImage
    self.win.setImage(self.pixmap)
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 2160, in setImage
    maxsize = self.screen().availableGeometry().size()
AttributeError: 'PicWin' object has no attribute 'screen'
Traceback (most recent call last):
  File "/home/dan/puddletag/puddlestuff/mainwin/artwork.py", line 108, in fill
    self.picwidget.setImages(pics, default=2)
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 2044, in setImages
    self.currentImage = default
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 1953, in _setCurrentImage
    self.win.setImage(self.pixmap)
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 2160, in setImage
    maxsize = self.screen().availableGeometry().size()
AttributeError: 'PicWin' object has no attribute 'screen'
Traceback (most recent call last):
  File "/home/dan/puddletag/puddlestuff/mainwin/artwork.py", line 108, in fill
    self.picwidget.setImages(pics, default=2)
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 2044, in setImages
    self.currentImage = default
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 1953, in _setCurrentImage
    self.win.setImage(self.pixmap)
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 2160, in setImage
    maxsize = self.screen().availableGeometry().size()
AttributeError: 'PicWin' object has no attribute 'screen'
Traceback (most recent call last):
  File "/home/dan/puddletag/puddlestuff/mainwin/funcs.py", line 197, in extended_tags
    win = helperwin.ExTags(files=status['selectedfiles'], parent=parent)
  File "/home/dan/puddletag/puddlestuff/helperwin.py", line 719, in __init__
    self.loadFiles(files)
  File "/home/dan/puddletag/puddlestuff/helperwin.py", line 889, in loadFiles
    self._loadsingle(audio)
  File "/home/dan/puddletag/puddlestuff/helperwin.py", line 973, in _loadsingle
    self.piclabel.setImages(deepcopy(images))
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 2044, in setImages
    self.currentImage = default
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 1953, in _setCurrentImage
    self.win.setImage(self.pixmap)
  File "/home/dan/puddletag/puddlestuff/puddleobjects.py", line 2160, in setImage
    maxsize = self.screen().availableGeometry().size()
AttributeError: 'PicWin' object has no attribute 'screen'
dan@XPS-8940:~/puddletag$ 

```
The last Traceback (File "/home/dan/puddletag/puddlestuff/mainwin/funcs.py", line 197, in extended_tags)
was the entry that occurred when I clicked the option for "Extended Tags", and nothing happened afterward.

**Comment by dannn-o** [comment]
![Screenshot from 2022-09-06 20-38-32](https://user-images.githubusercontent.com/17674969/188763777-2f307513-84bf-4de8-83af-9a02c4ec4837.png)

I'm not sure if there is a 'standard' way of checking the QT version, but Synaptic shows v5.12.8 as well for the "qt5-default" package.  If 5.14 is needed, is there are safe and easy way to upgrade?  I have a test VM I can use if you want me to
run some specific scenarios.

**Comment by dannn-o** [comment]
Thanks for including those extra resources.  Two things to consider:
1. Mentioning the requirement for QT version >= 5.14 in the list of "Dependencies" ([https://github.com/puddletag/puddletag](https://github.com/puddletag/puddletag)) would help.
2. If possible, adding backward compatibility for older QT versions to avoid the issue would be even better.  The version 1.2.0 (Appimage) installation performs the "Extended Tags" function perfectly.

**Comment by dannn-o** [comment]
I understand the nature of AppImages containing code & dependencies in a standalone "container", but my point was more about a workaround to support 'older' QT versions with possible If-Then-Else logic (i.e. If QT < v 5.14, then execute logic like 1.2.0 AppImage is doing, Else use newer `screen()` method).  Again, if the QT 5.14 dependency were more clearly indicated in the
section listing dependencies, that might help users evaluate their options for implementation.

I don't want to veer off into the weeds too much, so I'll just say that instead of upgrading my OS (I am normally an early adopter of new versions, but there aren't any new compelling features for me in Mint 21...yet), I'll stick with my dual setup (source/2.2.0 for reviewing tags, AppImage/1.2.0 for editing/correcting them) for now, which I find more convenient than setting up a Python virtual environment.  

Anyway, I appreciate the work done by you and the other contributors on this app.  Even with some of the issues like this, I find it's easier to use and has more functionality than the other ID3 editors available for Linux.
