### ISSUE TITLE
Startup crash: Debian Bullseye

### ISSUE THREAD

**Issue by diorn** [puddletag/puddletag#758]
Hello,
When running puddletag getting this error.
Any help is appreciated!

Traceback (most recent call last):
  File "/usr/local/bin/puddletag", line 4, in <module>
    __import__('pkg_resources').run_script('puddletag==2.2.0', 'puddletag')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/puddletag-2.2.0-py3.9.egg/EGG-INFO/scripts/puddletag", line 328, in <module>
    from PyQt5.QtGui import QIcon
ImportError: /usr/local/lib/python3.9/dist-packages/PyQt5-5.15.7-py3.9-linux-x86_64.egg/PyQt5/QtGui.abi3.so: undefined symbol: _ZdaPvm, version Qt_5

**Comment by sandrotosi** [comment]
Debian stable aka bullseye doesnt have a new-enough pyqt5 to run puddletag, which you installed from source and not the debian package. Nothing we can do about it, closing
