### ISSUE TITLE
Puddletag 2.2.0 does not run after install

### ISSUE THREAD

**Issue by canedmonkey** [puddletag/puddletag#826]
Mint 21.1
Puddletag 2.2.0

Puddletag does not run after install. Terminal shows this error:

`

Traceback (most recent call last):
  File "/usr/local/bin/puddletag", line 4, in <module>
    __import__('pkg_resources').run_script('puddletag==2.2.0', 'puddletag')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.10/dist-packages/puddletag-2.2.0-py3.10.egg/EGG-INFO/scripts/puddletag", line 328, in <module>
    from PyQt5.QtGui import QIcon
ImportError: /usr/local/lib/python3.10/dist-packages/PyQt5-5.15.7-py3.10-linux-x86_64.egg/PyQt5/QtGui.abi3.so: undefined symbol: _ZdaPvm, version Qt_5

`

**Comment by canedmonkey** [comment]
You guess wrong as I did not install build/install PyQt from source. All I did was install Linux Mint and then install puddletag so if PyQt5 is installed in a weird place, that's where Mint put it.

I havent been able to get to puddletag to run properly on Linux Mint since v19 so it looks to me like it is no longer compatible with Linux Mint.

It's a shame but your dismissive attitude suggests you couldnt care less.
