### ISSUE TITLE
Cannot add keyboard shortcut, Shortcut field is filled with [modifier]+<PyQts.QtGui.QKeySequence object at 0x7F624535dee0>

### ISSUE THREAD

**Issue by hsandt** [puddletag/puddletag#827]
### Current Behavior

When I try to add a shortcut in Preferences > Shortcuts > Shortcut column > input key combination, the Shortcut cell is filled with an odd:

> [modifier]+<PyQts.QtGui.QKeySequence object at 0x7F624535dee0>

For instance, with Ctrl+Shift+F for Format action, I see:

> Ctrl+Shift+<PyQts.QtGui.QKeySequence object at 0x7F624535dee0>

![image](https://github.com/puddletag/puddletag/assets/1067772/6e6dbab9-bc96-4e6d-aac5-f25a70aeee6d)

If there is no modifier, such as F3, I just see `<PyQts.QtGui.QKeySequence object at 0x7F...>`

I clicked OK and tested the shortcut, but it didn't work. Back in the Preferences > Shortcuts, I noticed the cell had been reset to blank, so the shortcut was not confirmed.

![image](https://github.com/puddletag/puddletag/assets/1067772/dcccee66-b8d2-4e34-a2dd-bbef0d731101)

### Expected Behavior

The cell should be filled withe proper key name, here Ctrl+Shift+F

### Steps To Reproduce

1. Open Preferences
2. Select Shortcuts page
3. Double-click on some cell
4. Enter keyboard combination

### Information about your system

_Note: I saw no "Report a problem" function in the "Help" menu of the application as mentioned in the Tip above this field. However, I could find versions in About puddletag, some extra stuff like Mutagen, and Qt version in About Qt; but no version for Python itself. There is a Help > Bug Tracker item but it leads to the old archive: https://code.google.com/archive/p/puddletag/_

Puddletag: 2.0.1
OS: Ubuntu 22.04 with Unity desktop
Python: ?
Qt: 5.15.3
PyQt: 5.15.6
Mutagen: 1.46.0
Pyparsing: 2.4.7

### Anything else?

I ran puddletag in terminal to check the console log when pressing the key combination:

Holding Ctrl:

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/puddlestuff/shortcutsettings.py", line 112, in paintEvent
    painter.drawRect(left - size, size * 0.5, size, size)
TypeError: arguments did not match any overloaded call:
  drawRect(self, QRectF): argument 1 has unexpected type 'float'
  drawRect(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawRect(self, QRect): argument 1 has unexpected type 'float'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?

Holding Shift:

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/puddlestuff/shortcutsettings.py", line 112, in paintEvent
    painter.drawRect(left - size, size * 0.5, size, size)
TypeError: arguments did not match any overloaded call:
  drawRect(self, QRectF): argument 1 has unexpected type 'float'
  drawRect(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawRect(self, QRect): argument 1 has unexpected type 'float'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?

And pressing F:

> QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?

**Comment by hsandt** [comment]
Thank you, I `pip install puddletag -U` to upgrade my existing installation (I also removed my Ubuntu package install which I was not using at all anyway as the PATH would give priority to pip installations), and in v2.4.0 it works fine. I hit https://github.com/puddletag/puddletag/issues/975 but it didn't block the install.

As a result, it also helped me fix other issues I reported that were fixed in v2.4.0!
