### ISSUE TITLE
Stuck on "Please wait... Writing 1 of (X)..."

### ISSUE THREAD

**Issue by TheArgentinian** [puddletag/puddletag#830]
### Current Behavior

New tags are not written when using Tag Sources. I can cancel the process and close the program, so it's not a freeze.

Here's the terminal output:

> puddletag
puddletag Version: 2.0.1
Locale: es_ES
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 895, in threadfunc
    temp = next(f)
  File "/usr/lib/python3/dist-packages/puddlestuff/puddletag.py", line 740, in func
    update = setRowData(row, f, undo=True)
  File "/usr/lib/python3/dist-packages/puddlestuff/tagmodel.py", line 1102, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
  File "/usr/lib/python3/dist-packages/puddlestuff/util.py", line 318, in write
    audio.update(user_only)
  File "/usr/lib/python3/dist-packages/puddlestuff/tagmodel.py", line 288, in update
    super(ModelTag, self).update(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/puddlestuff/audioinfo/util.py", line 867, in update
    self[key] = value
  File "/usr/lib/python3/dist-packages/puddlestuff/tagmodel.py", line 268, in __setitem__
    super(ModelTag, self).__setitem__(key, value)
  File "/usr/lib/python3/dist-packages/puddlestuff/audioinfo/util.py", line 473, in f
    return func(self, mapping[key], value)
  File "/usr/lib/python3/dist-packages/puddlestuff/audioinfo/id3.py", line 980, in __setitem__
    self.__tags.update(create_ufid(key, value))
  File "/usr/lib/python3/dist-packages/puddlestuff/audioinfo/id3.py", line 528, in create_ufid
    frame = id3.UFID(owner, value)
  File "/usr/lib/python3/dist-packages/mutagen/id3/_frames.py", line 63, in __init__
    setattr(self, checker.name, val)
  File "/usr/lib/python3/dist-packages/mutagen/id3/_frames.py", line 76, in __setattr__
    self._setattr(name, checker.validate(self, value))
  File "/usr/lib/python3/dist-packages/mutagen/id3/_specs.py", line 430, in validate
    raise TypeError("%s has to be bytes" % self.name)
TypeError: data has to be bytes

### Expected Behavior

Tag files  with metadata from Musicbrainz.

### Steps To Reproduce

1) add a folder of mp3s. 
2) use Tag Sources and Musicbrainz as source 
3) After finding the album, select it . 
4) Click on write 
5) "Please wait... Writing 1 of (X)..." pop-up appears and gets stuck there

### Information about your system

Puddletag: 2.0.1
OS: Linux
Python: 3.10.12
PyQt: 5.15.3

**Comment by TheArgentinian** [comment]
> This is just an educated guess but `id3.UFID` in the traceback and hanging threads while writing tags sounds very much like what was fixed in #693. Could you please confirm that the problem doesn't happen with the most recent version of puddletag (namely v2.2.0)?

Oh, wow, I had no idea I had such an outdated version. I just installed it from Synaptic. Is there a way to update it without all that troublesome steps on this Github page? Like just adding an official ppa?

**Comment by TheArgentinian** [comment]
> you can try downloading and installing that one single package. But be warned, I have no idea if it works and how your system likes it.

That worked. Thanks!

BTW, how can I see the Album Artist tag (for albums with feat.)? And what about Disc title (for boxsets)?
