### ISSUE TITLE
Crashes when editing M4A files?

### ISSUE THREAD

**Issue by BobbyWibowo** [puddletag/puddletag#850]
### Current Behavior

```log
$ puddletag
puddletag Version: 2.2.0
Locale: C
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mutagen/mp4/__init__.py", line 722, in __render_integer
    if cdata.int8_min <= v <= cdata.int8_max and min_bytes <= 1:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 1287, in setModelData
    model.setData(index, editor.text())
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 2150, in modded_setData
    return set_data(index, value, role)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 1044, in setData
    ret = self.setRowData(index.row(), {tag: newvalue}, undo=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 1099, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/util.py", line 330, in write
    audio.save()
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/mp4.py", line 435, in save
    audio.update(newtag)
  File "/usr/lib/python3.11/site-packages/mutagen/_util.py", line 498, in update
    self.__setitem__(key, value)
  File "/usr/lib/python3.11/site-packages/mutagen/_file.py", line 74, in __setitem__
    self.tags[key] = value
    ~~~~~~~~~^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/mp4/__init__.py", line 372, in __setitem__
    self._render(key, value)
  File "/usr/lib/python3.11/site-packages/mutagen/mp4/__init__.py", line 388, in _render
    return render_func(self, key, value, *render_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/mp4/__init__.py", line 739, in __render_integer
    raise MP4MetadataValueError(e)
mutagen.mp4.MP4MetadataValueError: '<=' not supported between instances of 'int' and 'bytes'
[1]    912838 IOT instruction (core dumped)  puddletag
```

### Expected Behavior

No crash

### Steps To Reproduce

1. Edit an MP4 file
2. Try to change a value, for example Title
3. Crashes

### Information about your system

Puddletag: 2.2.0.r125.gcc19fda
OS: EndeavourOS, kernel 6.6.4-arch1-1
Python: 3.11.6
PyQt: 5.15.10
Qt: 5.15.11
Mutagen: 1.47.0
PyParsing: 3.1.1
ConfigObj: 5.0.8
Unidecode: 1.3.7
lxml: 4.9.2
pyacoustid: not installed
audioread: not installed
Levenshtein: 0.23.0
Chromaprint: not installed

**Comment by fir3-1ce** [comment]
im using the latest dev build and ive run into this problem too, only my gui didnt crash it just hanged on tagging the first track forever. i was able to hit cancel

**Comment by BobbyWibowo** [comment]
@corubba Yeah, can confirm that it works generally fine with some other M4A files. Here's a zip of one I can confirm to cause crashes: https://i.fiery.me/TDUTu4tj.7z

**Comment by naul06** [comment]
I'm having the exact same issue on puddletag 2.5.0 and deleting the internal IDs, as recommended, does fix it. More specifically, I have found that the "itunescomposerid" tag is the culprit, as deleting it is enough not to crash the program and to allow further modifications. Strangely, though, it was already covered by @corubba's commit on #865.

**Comment by corubba** [comment]
Is the error exactly the same `mutagen.mp4.MP4MetadataValueError: '<=' not supported between instances of 'int' and 'bytes'` (the order of the two mentioned types matters)?

Looking at the PR, specifically regarding `itunescomposerid`, it is still mapped as text and not as integer. And there is no mention/explanation of it (thanks past-me), so it could either be a mistake or deliberate (because some of theses are really strings). Which reminds me again why I hate these iTunes tags: there is no (official) specification for them where you can simply look it up, it's all just reverse-/guess-work.

**Comment by naul06** [comment]
The error is actually `mutagen.mp4.MP4MetadataValueError: '<=' not supported between instances of 'int' and 'str'` this time around. My bad, should've sent this in advance.
