### ISSUE TITLE
Extended Tags close application

### ISSUE THREAD

**Issue by Antonio-52** [puddletag/puddletag#877]
### Current Behavior

1. select a music file in the right (main) panel
2. right-click to show pop-up menu
3. click "Extended Tags"
4. the application closes.

### Expected Behavior

1. select a music file in the right (main) panel
2. right-click to show pop-up menu
3. click "Extended Tags"
4. the Extended Tags window opens.

### Steps To Reproduce

1. select a music file in the right (main) panel
2. right-click to show pop-up menu
3. click "Extended Tags"

### Information about your system

Puddletag: 2.2.0
OS: Ubuntu Core 20
Python: 3.8.10
PyQt: 5.14.1
Qt: 5.12.8
Mutagen: 1.44.0
PyParsing: 2.4.6
ConfigObj: 5.0.6
lxml: not installed
pyacoustid: not installed
audioread: not installed
Levenshtein: not installed
Chromaprint: not installed

### Anything else?

Note: It seems to me that this behaviour occurs with .flac music files, not with .mp3

**Comment by Antonio-52** [comment]
Hi!
I run Puddletag from the terminal but the behaviour is a little different: click Extended Tags for a .flac file does not shut off the application but, simply, does not open any Extende Tags window.
Here is the listing:
<code>antonio@HP-Laptop-15:~$ puddletag
puddletag Version: 2.2.0
Locale: it_IT
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/puddlestuff/mainwin/funcs.py", line 197, in extended_tags
    win = helperwin.ExTags(files=status['selectedfiles'], parent=parent)
  File "/usr/lib/python3/dist-packages/puddlestuff/helperwin.py", line 719, in __init__
    self.loadFiles(files)
  File "/usr/lib/python3/dist-packages/puddlestuff/helperwin.py", line 889, in loadFiles
    self._loadsingle(audio)
  File "/usr/lib/python3/dist-packages/puddlestuff/helperwin.py", line 973, in _loadsingle
    self.piclabel.setImages(deepcopy(images))
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 2044, in setImages
    self.currentImage = default
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 1953, in _setCurrentImage
    self.win.setImage(self.pixmap)
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 2160, in setImage
    maxsize = self.screen().availableGeometry().size()
AttributeError: 'PicWin' object has no attribute 'screen'
</code>

**Comment by Antonio-52** [comment]
Ok, but I cannot upgrade the OS on my PC because of small free space on the disk.
But:
- there still are a lot of PC with Ubuntu 20, not yet upgraded to 22.
- I 'd liked a warning message during installation of puddletag.
--
Antonio Angelo

-------- Messaggio originale --------
12/03/24 00:08, Corubba  ha scritto:
