### ISSUE TITLE
Attach an image closes the application

### ISSUE THREAD

**Issue by Antonio-52** [puddletag/puddletag#879]
### Current Behavior

1. select an mp3 music file in the right (main) panel
2. right-click to show pop-up menu
3. click "Extended Tags"
4. click the righthand "+" to Add Image
5. select the image to be loaded (in my case, about 1-2 MB)
6. the application closes.

### Expected Behavior

1. select an mp3 music file in the right (main) panel
2. right-click to show pop-up menu
3. click "Extended Tags"
4. Extended Tags window opens
5. click the righthand "+" to Add Image
6. select the image to be loaded (in my case, about 1-2 MB)
7. the image appears in the Extended Tags windows
8. click OK, the Extended Tags windows closes and the image is saved into the mp3 file.

### Steps To Reproduce

1. select an mp3 music file in the right (main) panel
2. right-click to show pop-up menu
3. click "Extended Tags"
4. click the righthand "+" to Add Image
5. select the image to be loaded (in my case, about 1-2 MB)

### Information about your system

Puddletag: 2.2.0
OS: Ubuntu Core 20
Python: 3.8.10
PyQt: 5.14.1
Qt: 5.12.8
Mutagen: 1.44.0
PyParsing: 2.4.6
ConfigObj: 5.0.6
lxml: not installed
pyacoustid: not installed
audioread: not installed
Levenshtein: not installed
Chromaprint: not installed

### Anything else?

I refer to an mp3 music file because a flac file shutdown the application as soon as I attempt to open the Extended Tags window.

**Comment by Antonio-52** [comment]
Hi!
I run Puddletag in the terminal but the behaviour is a little different then before:
1. select an mp3 music file in the right (main) panel
2. right-click to show pop-up menu
3. click "Extended Tags"
4. click the righthand "+" to Add Image
5. select the image to be loaded (in my case, about 1-2 MB)
6. the image is shown in the Extended Tags window
7. close the Extended Tags
8. reopen Extended Tags window
9. no image shown for the same mp3 file.

Here is the listing:
<code>antonio@HP-Laptop-15:~$ puddletag
puddletag Version: 2.2.0
Locale: it_IT
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 1835, in addImage
    self.setImages([pic])
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 2044, in setImages
    self.currentImage = default
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 1953, in _setCurrentImage
    self.win.setImage(self.pixmap)
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 2160, in setImage
    maxsize = self.screen().availableGeometry().size()
AttributeError: 'PicWin' object has no attribute 'screen'
</code>

**Comment by sandrotosi** [comment]
@corubba would it make sense to print a warning (or even stopping execution, with a popup maybe (so it's not hidden in the terminal)) if puddletag detects qt <5.14?
