### ISSUE TITLE
Puddletag fails to start after upgrading pyparsing to 3.1.2

### ISSUE THREAD

**Issue by k0mmsussert0d** [puddletag/puddletag#884]
### Current Behavior

Pyparsing crashes during the start-up. Following output is printed:

```
puddletag Version: 2.3.0
Locale: en_US
Traceback (most recent call last):
  File "/usr/bin/puddletag", line 352, in <module>
    from puddlestuff.puddletag import MainWin
  File "/usr/lib/python3.11/site-packages/puddlestuff/puddletag.py", line 14, in <module>
    from . import mainwin
  File "/usr/lib/python3.11/site-packages/puddlestuff/mainwin/__init__.py", line 4, in <module>
    from . import dirview
  File "/usr/lib/python3.11/site-packages/puddlestuff/mainwin/dirview.py", line 12, in <module>
    from ..tagmodel import has_previews
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 32, in <module>
    from .audio_filter import parse as filter_audio
  File "/usr/lib/python3.11/site-packages/puddlestuff/audio_filter.py", line 183, in <module>
    bool_expr.enablePackrat()
  File "/usr/lib/python3.11/site-packages/pyparsing/util.py", line 265, in _inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyparsing/core.py", line 1132, in enable_packrat
    ParserElement.packrat_cache = _FifoCache(cache_size_limit)  # type: ignore[assignment]
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyparsing/util.py", line 105, in __init__
    keyring = [object()] * size
              ~~~~~~~~~~~^~~~~~
TypeError: can't multiply sequence by non-int of type 'Forward'
```

Downgrading `pyparsing` to 3.1.1 resolves the issue.

### Expected Behavior

Puddletag should start normally with installed dependencies as provided in `requirements.txt` file.

### Steps To Reproduce

1. Attempt to run puddletag

### Information about your system

Puddletag: 2.3.0
OS: Arch Linux x86_64 (6.7.9-arch1-1)
Python: 3.11.8
PyQt: 5.15.10

**Comment by Arnvidr** [comment]
Can confirm that #880 seems to fix it for me. pyparsing has also fixed this upstream, if there's a 3.1.3 version in the near future.

**Comment by vinivosh** [comment]
Can confirm the cause too. Downgrading pyparsing to 3.1.1 has fixed the Puddletag crash on startup.

**Comment by Switch123456789** [comment]
I am on Arch and after upgrading the `puddletag-git` aur-package to the latest version, it works fine again.
