### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by audiomuze** [puddletag/puddletag#885]
### Current Behavior

Puddletag crashing on launch:

$ python /home/x/git/puddletag/puddletag .
puddletag Version: 2.3.0, Changeset: 6fe83efa22804b224c83ed188064d54a630aaabc
QFont::fromString: Invalid description 'Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Hack,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
Locale: en_US
Traceback (most recent call last):
  File "/home/x/git/puddletag/puddletag", line 352, in <module>
    from puddlestuff.puddletag import MainWin
  File "/home/x/git/puddletag/puddlestuff/puddletag.py", line 14, in <module>
    from . import mainwin
  File "/home/x/git/puddletag/puddlestuff/mainwin/__init__.py", line 4, in <module>
    from . import dirview
  File "/home/x/git/puddletag/puddlestuff/mainwin/dirview.py", line 12, in <module>
    from ..tagmodel import has_previews
  File "/home/x/git/puddletag/puddlestuff/tagmodel.py", line 32, in <module>
    from .audio_filter import parse as filter_audio
  File "/home/x/git/puddletag/puddlestuff/audio_filter.py", line 183, in <module>
    bool_expr.enablePackrat()
  File "/usr/lib/python3.11/site-packages/pyparsing/util.py", line 265, in _inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyparsing/core.py", line 1132, in enable_packrat
    ParserElement.packrat_cache = _FifoCache(cache_size_limit)  # type: ignore[assignment]
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyparsing/util.py", line 105, in __init__
    keyring = [object()] * size
              ~~~~~~~~~~~^~~~~~
TypeError: can't multiply sequence by non-int of type 'Forward'


### Expected Behavior

Puddletag launch.


### Steps To Reproduce

$ python /home/x/git/puddletag/puddletag .

### Information about your system

Puddletag: puddletag Version: 2.3.0, Changeset: 6fe83efa22804b224c83ed188064d54a630aaabc
OS: 6.7.9-arch1-1
Python:  3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801] on linux
PyQt: Qt version 5.15.12

### Anything else?

_No response_

**Comment by audiomuze** [comment]
Duplicate of https://github.com/puddletag/puddletag/issues/884
