### ISSUE TITLE
ImportError: cannot import name 'delimited_list' from 'pyparsing' (/usr/lib/python3/dist-packages/pyparsing.py)

### ISSUE THREAD

**Issue by punishyourmachine** [puddletag/puddletag#916]
### Current Behavior

Hello,  installed Puddletag from source code by installing dependencies and cloning GIT.  Cannot start Puddletag, I get the following error.  I'm not sure if I missed something, or if there is a bug.  Thank you.

puddletag Version: 2.4.0, Changeset: f46f6604d6e4bead20652c1c6cf3026f64508432
Locale: en_US
Traceback (most recent call last):
  File "/home/david/puddletag/./puddletag", line 352, in <module>
    from puddlestuff.puddletag import MainWin
  File "/home/david/puddletag/puddlestuff/puddletag.py", line 13, in <module>
    from . import m3u, genres
  File "/home/david/puddletag/puddlestuff/m3u.py", line 11, in <module>
    from .findfunc import tagtofilename
  File "/home/david/puddletag/puddlestuff/findfunc.py", line 11, in <module>
    from pyparsing import (CharsNotIn, Combine, Literal, OneOrMore, Optional, ParserElement,
ImportError: cannot import name 'delimited_list' from 'pyparsing' (/usr/lib/python3/dist-packages/pyparsing.py)

### Expected Behavior

I expect Puddletag to start.

### Steps To Reproduce

install dependencies.
clone GIT.

cd puddletag
./puddletag

Puddletag doesn't start, shows error messages.

### Information about your system

Puddletag: 2.4.0, Changeset: f46f6604d6e4bead20652c1c6cf3026f64508432
OS: Linux Mint 21.3
Python: 3.10.6-1~22.04
PyQt: 5.15.6+dfsg-1ubuntu3

**Comment by sandrotosi** [comment]
it seems you have some modules missing in your systems, it's probably better if you follow the steps to create a virtualenv: https://github.com/puddletag/puddletag#:~:text=%27%0A./puddletag-,Alternatively,-you%20can%20use

**Comment by Perkolator** [comment]
That's rather disappointing. That puddletag 2.4.0 and onwards won't even work with a very new ubuntu base. Only supporting very new rolling distros?

**Comment by sandrotosi** [comment]
> That's rather disappointing. That puddletag 2.4.0 and onwards won't even work with a very new ubuntu base. Only supporting very new rolling distros?

very new? the version of mint you're using is based on ubuntu 22.04, which is more than 2 years old. that means there has been 2+ years of new packages/modules/projects/applications released in between.

**Comment by Perkolator** [comment]
Actually, my Mint is based on 20.04. I was just commenting that even the 22.04 is not anymore supported. 2+ years is not that much for software support really.

**Comment by sandrotosi** [comment]
does really make it any better than your system is even older :)

but the main point is: you are *not* using the distro package, since the single reason any distribution exists is to provide a cohesive experience amongst all its packages.

you want to install puddletag from source (likely because your distro does not and will not provide the new version as a package), but you expect it to work with 4 years old system-installed modules (which likely means they are even older).

That is not going to work.

if you still want to use puddletag/2.4.0, and you should because it's great :) , please do follow the steps to use a virtual environment.

And be aware that even python interpreter may be too old and not support all the newer modules versions we requires.

**Comment by Perkolator** [comment]
The fact still remains that there are lots of users that can't use the newest versions of your software. Some developers give long support, you don't, that's your prerogative. There are also other solutions that have gained a lot of traction, e.g. Flatpak, or AppImage.

**Comment by sandrotosi** [comment]
i understand this is not the answer you were expecting, but this is what it is. Im going to lock this issue now, ans it's no longer productive.
