### ISSUE TITLE
Puddletag 2.4.0 crashed, I solved crash and a lot of errors in console

### ISSUE THREAD

**Issue by RafaelLinux** [puddletag/puddletag#919]
### Current Behavior

I launch Puddletag and crashed. After taking a look to what was necessary to run it, I installed  python311-Unidecode and python311-PyQt6  and now it doesn't crash, but shows a lot of errors in console.

### Expected Behavior

To launch as always

### Steps To Reproduce

1. Click on "puddletag" icon or launch from console without errors

### Information about your system

Puddletag: 2.4.0
OS:  opensuse Tumbleweed
Python:  3.11
PyQt:  python311-PyQt6-sip-13.6.0-2.5.x86_64

### Anything else?

Console ouuput errors
```
~> puddletag 
puddletag Version: 2.4.0
Locale: es_DO
[2024-07-04 23:09:45,549]ERROR:Error loading file /home/Music/song_32348.mp3
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/puddlestuff/puddleobjects.py", line 675, in gettag
    return audioinfo.Tag(f)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 329, in ReplacementTag
    return filetypes[extensions[match.groups()[0]][0]][1](filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 158, in __init__
    super(ModelTag, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/id3.py", line 818, in __init__
    util.MockTag.__init__(self, filename)
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/util.py", line 752, in __init__
    self.link(filename)
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/id3.py", line 1012, in link
    tags, audio = self.load(filename, id3_filetype)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/util.py", line 854, in load
    audio = filetype(filename)
            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/id3.py", line 772, in load
    return super(ID3FileType, self).load(filename, ID3, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/id3/_file.py", line 420, in load
    self.info = self._Info(fileobj, offset)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/mp3/__init__.py", line 401, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
[2024-07-04 23:09:45,623]ERROR:Error loading file /home/Music/song_998273.mp3
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/puddlestuff/puddleobjects.py", line 675, in gettag
    return audioinfo.Tag(f)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 329, in ReplacementTag
    return filetypes[extensions[match.groups()[0]][0]][1](filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 158, in __init__
    super(ModelTag, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/id3.py", line 818, in __init__
    util.MockTag.__init__(self, filename)
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/util.py", line 752, in __init__
    self.link(filename)
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/id3.py", line 1012, in link
    tags, audio = self.load(filename, id3_filetype)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/util.py", line 854, in load
    audio = filetype(filename)
            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/puddlestuff/audioinfo/id3.py", line 772, in load
    return super(ID3FileType, self).load(filename, ID3, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/id3/_file.py", line 420, in load
    self.info = self._Info(fileobj, offset)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mutagen/mp3/__init__.py", line 401, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame

```

Suggestion: Please, an AppImage will solve this kind of issues for any distro.

**Comment by sandrotosi** [comment]
how did you install 2.4.0? if it's from the distro packages, please follow up with them first.

**Comment by RafaelLinux** [comment]
`opi puddletag` (or download from any of [these](https://software.opensuse.org/package/puddletag) non official repositories).

There is no official version for openSUSE, that is why I ask for an AppImage version that will works in any distro.

**Comment by sandrotosi** [comment]
we are *not* going to provide appimage or flatpack in the foreseeable future, so please do no ask for it.

you seem to have it installed using a third-party package, so please reach out to the service you download it from.

closing this report now.

**Comment by RafaelLinux** [comment]
I don't understand why the comment "don't ask about it". If I hadn't asked, I wouldn't have known that you have no intention of releasing versions in those formats. It's a good idea to, as I said, avoid problems between distributions, but after the blunt answer you give, other users of distributions where there are also problems with libraries, simply won't use puddletag. Not all users have the knowledge, and the time to go around informing or investigating about possible problems.

Thanks anyway

**Comment by sandrotosi** [comment]
there are several items to unpack here:

1. github allows to search in past issues/PRs, by doing so you'd discovered our position on binary distributions.
2. if a user is not technically savvy to install a package from source, then they usually just use what their distro provides, which means they should receive support from the distro if something goes wrong (not the upstream project directly)
3. if a user is at an intermediate tech level and wants to use third-party distributions for softwares they want a new version for, then they should receive support from those third-party systems (not the upstream project directly)
4. if a user is at an advanced level, and feel the need to use the latest and greatest, we provide some example on how to do so in our documentation https://github.com/puddletag/puddletag?tab=readme-ov-file#source-code

@RafaelLinux it seems you want to do the least amount of work to get the latest version (third party distribution chanels) and just throw your hands in the air if something goes wrong (instead of reaching out to who packaged the software you installed). I'm afraid that's really not how it works: plenty of users are satisfied with the way we release software and at the end of the day our license clearly states that this program is provided "as is" (GPL3.0, 15. Disclaimer of Warranty)

i'm locking this ticket to avoid further out-of-topic comments.
