### ISSUE TITLE
Crash when filtering by "-" character

### ISSUE THREAD

**Issue by RafaelLinux** [puddletag/puddletag#929]
### Current Behavior

When I look for the ‘-’ character and click ‘Go’, Puddletag exits.

It doesn't fail when searching for other characters, such as ‘_’. I have tried in other folders with other files, and the same result.

Crash output:
```
> puddletag 
puddletag Version: 2.4.0
Locale: es_DO
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/puddlestuff/audio_filter.py", line 194, in parse
    res = bool_expr.parse_string(expr)[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyparsing/core.py", line 1200, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected 'NOT' term, found '-'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 1546, in applyFilter
    self.model().applyFilter(pattern, matchcase)
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 664, in applyFilter
    filtered = [(filter_audio(a, pattern), a) for a in self.taginfo]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/tagmodel.py", line 664, in <listcomp>
    filtered = [(filter_audio(a, pattern), a) for a in self.taginfo]
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/puddlestuff/audio_filter.py", line 195, in parse
    except ParseException as e:
           ^^^^^^^^^^^^^^
NameError: name 'ParseException' is not defined. Did you mean: 'BaseException'?
Abortado (`core' generado)

```

### Expected Behavior

To show only files with "-" character in filename.

### Steps To Reproduce

1 - Enter the character ‘-’ in the field ‘Filter’.
2 - Press the ‘Go’ button

### Information about your system

Puddletag: 2.4.0
Python: 3.11.9
PyQt: 5.15.10
Qt: 5.15.14
Mutagen: 1.47.0
PyParsing: 3.1.2
ConfigObj: 5.0.8
Unidecode: 1.3.8
lxml: 5.2.2
pyacoustid: not installed
Levenshtein: 0.25.1

**Comment by RafaelLinux** [comment]
I see... that problem was also reported by me!!!! XD
