### ISSUE TITLE
Load Artwork

### ISSUE THREAD

**Issue by Scramshaw** [puddletag/puddletag#931]
### Current Behavior

Hello,

I've been using the Load Artwork function with great success but all of a sudden it has stopped responding (after approximately 12.5k successful amendments).

When I try to run the function the dialogue box hangs. Is there a cache for images or similar that I need to clear?

I've tried selecting the minimum amount of mp3s (2) and changing previous successes which now fail.

I can still add artwork "manually" for the time being but this function has prevented a almost certain future RSI.

Thanx for reading,
Sam

![New Project](https://github.com/user-attachments/assets/8558502f-84e9-405a-9fb5-02f32bf3f742)

### Expected Behavior

Artwork to be attached to mp3 in bulk

### Steps To Reproduce

Action > Functions > Load Artwork

Filenames to check: *.mp3
Default description: %album%
Shortcut assigned: CTRL + ALT + A

### Information about your system

Puddletag: 2.0.1
OS: Linux Mint Virginia 
Python: Unsure
PyQt: 5.15.6

### Anything else?

This is a great program! Where's the donation button?

**Comment by Scramshaw** [comment]
Thanx for the prompt response.

Apologies for my density. New to the platform and still working my way around.

This is the output:

> puddletag Version: 2.0.1
> Locale: en_GB
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/mutagen/id3/_util.py", line 85, in to_str
>     bytes_[index] = value & mask
> IndexError: bytearray index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 2383, in run
>     self.retval = self.command()
>   File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 895, in threadfunc
>     temp = next(f)
>   File "/usr/lib/python3/dist-packages/puddlestuff/puddletag.py", line 740, in func
>     update = setRowData(row, f, undo=True)
>   File "/usr/lib/python3/dist-packages/puddlestuff/tagmodel.py", line 1102, in setRowData
>     undo_val = write(audio, tags, self.saveModification, justrename)
>   File "/usr/lib/python3/dist-packages/puddlestuff/util.py", line 319, in write
>     audio.save()
>   File "/usr/lib/python3/dist-packages/puddlestuff/audioinfo/id3.py", line 1098, in save
>     audio.tags.save(v1=v1, v2_version=4)
>   File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 185, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 156, in wrapper
>     return func(self, h, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/mutagen/id3/_file.py", line 261, in save
>     data = self._prepare_data(
>   File "/usr/lib/python3/dist-packages/mutagen/id3/_file.py", line 208, in _prepare_data
>     new_framesize = BitPaddedInt.to_str(new_size - 10, width=4)
>   File "/usr/lib/python3/dist-packages/mutagen/id3/_util.py", line 89, in to_str
>     raise ValueError('Value too wide (>%d bytes)' % width)
> ValueError: Value too wide (>4 bytes)
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
>     with os.fdopen(os.open(pr_filename,
> FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_puddletag.1000.crash'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/mutagen/id3/_util.py", line 85, in to_str
>     bytes_[index] = value & mask
> IndexError: bytearray index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 2383, in run
>     self.retval = self.command()
>   File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 895, in threadfunc
>     temp = next(f)
>   File "/usr/lib/python3/dist-packages/puddlestuff/puddletag.py", line 740, in func
>     update = setRowData(row, f, undo=True)
>   File "/usr/lib/python3/dist-packages/puddlestuff/tagmodel.py", line 1102, in setRowData
>     undo_val = write(audio, tags, self.saveModification, justrename)
>   File "/usr/lib/python3/dist-packages/puddlestuff/util.py", line 319, in write
>     audio.save()
>   File "/usr/lib/python3/dist-packages/puddlestuff/audioinfo/id3.py", line 1098, in save
>     audio.tags.save(v1=v1, v2_version=4)
>   File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 185, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 156, in wrapper
>     return func(self, h, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/mutagen/id3/_file.py", line 261, in save
>     data = self._prepare_data(
>   File "/usr/lib/python3/dist-packages/mutagen/id3/_file.py", line 208, in _prepare_data
>     new_framesize = BitPaddedInt.to_str(new_size - 10, width=4)
>   File "/usr/lib/python3/dist-packages/mutagen/id3/_util.py", line 89, in to_str
>     raise ValueError('Value too wide (>%d bytes)' % width)
> ValueError: Value too wide (>4 bytes)

**Comment by Scramshaw** [comment]
P.S.
I'm having difficulty accessing the latest build although I think it's an issue with python and not puddletag.

Here is what is spitting out:

> ./puddletag
> puddletag Version: 2.4.0
> Locale: en_GB
> Traceback (most recent call last):
>   File "/home/hal/Downloads/puddletag-2.4.0/./puddletag", line 352, in <module>
>     from puddlestuff.puddletag import MainWin
>   File "/home/hal/Downloads/puddletag-2.4.0/puddlestuff/puddletag.py", line 13, in <module>
>     from . import m3u, genres
>   File "/home/hal/Downloads/puddletag-2.4.0/puddlestuff/m3u.py", line 11, in <module>
>     from .findfunc import tagtofilename
>   File "/home/hal/Downloads/puddletag-2.4.0/puddlestuff/findfunc.py", line 11, in <module>
>     from pyparsing import (CharsNotIn, Combine, Literal, OneOrMore, Optional, ParserElement,
> ImportError: cannot import name 'delimited_list' from 'pyparsing' (/usr/lib/python3/dist-packages/pyparsing.py)

**Comment by Scramshaw** [comment]
Hello. Thanx for getting back to me. I seem to have the libraries up-to-date. As I stated before, it was working perfectly fine until I reached around 25k entries (not all at the same time, I have artists in an alphabetical folder structure).

I've tried this on the secure build and the latest build on both mine and my partners laptop, both running Mint 21.3.

Python: 3.10.12
PyQt: 5.15.6
Qt: 5.15.3
Mutagen: 1.45.1
PyParsing: 3.1.2
ConfigObj: 5.0.6
Unidecode: 1.3.3
lxml: 4.8.0
pyacoustid: not installed
Levenshtein: not installed
