### ISSUE TITLE
Crash when modifying actions

### ISSUE THREAD

**Issue by Mangiola** [puddletag/puddletag#933]
### Current Behavior

Application crashes when attempting to create or delete steps for an action. Happens on every system I've tried (listed below). Log:

```
puddletag Version: 2.4.0
Locale: en_CA
Traceback (most recent call last):
  File "/home/USER/Projects/puddletag-master/puddlestuff/actiondlg.py", line 651, in remove
    self.updateExample()
  File "/home/USER/Projects/puddletag-master/puddlestuff/actiondlg.py", line 626, in updateExample
    tags = apply_actions(self.functions, self.example, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/Projects/puddletag-master/puddlestuff/findfunc.py", line 606, in apply_actions
    fields = parse_field_list(func.tag, audio)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/Projects/puddletag-master/puddlestuff/findfunc.py", line 502, in parse_field_list
    fields.extend([key for key in audio if key not in NOT_ALL])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
Aborted (core dumped)

```

### Expected Behavior

Modify actions without crashing.

### Steps To Reproduce

1. Fresh install. 
2. Open actions pane (Windows -> Actions).
3. Select "Standard", click edit button.
4. Select the first replace action, click remove button.

### Information about your system

Puddletag: 2.2.0, 2.4.0 & master as of writing
OS: Fedora 40, Opensuse Tumbleweed, Ubuntu 24.04 LTS. All running KDE Plasma.
Python: 3.12.3
PyQt: 5.15.10

### Anything else?

I haven't seen any other reports of this error despite it affecting basic app usage, so perhaps I'm overlooking something.

**Comment by Switch123456789** [comment]
For me it also crashes while a folder is loaded if no file is selected.
`Arch Linux` `v2.4.0`
