### ISSUE TITLE
Adding cover-art to a flac-file that exceeds the max allowed size (~16MB) crashes puddletag

### ISSUE THREAD

**Issue by Switch123456789** [puddletag/puddletag#937]
### Current Behavior

Puddletag crashes with the following console-output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/puddlestuff/puddletag.py", line 943, in writeOneToMany
    s(self)
  File "/usr/lib/python3.12/site-packages/puddlestuff/puddleobjects.py", line 852, in s
    errors = next(f)
             ^^^^^^^
  File "/usr/lib/python3.12/site-packages/puddlestuff/puddletag.py", line 868, in func
    update = setRowData(row, f, undo=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/puddlestuff/tagmodel.py", line 1115, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/puddlestuff/util.py", line 333, in write
    audio.save()
  File "/usr/lib/python3.12/site-packages/puddlestuff/audioinfo/vorbis.py", line 227, in save
    audio.save()
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/flac.py", line 859, in save
    self._save(filething, self.metadata_blocks, deleteid3, padding)
  File "/usr/lib/python3.12/site-packages/mutagen/flac.py", line 875, in _save
    data = MetadataBlock._writeblocks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/flac.py", line 153, in _writeblocks
    data += cls._writeblock(block)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/flac.py", line 136, in _writeblock
    raise error("block is too long to write")
mutagen.flac.error: block is too long to write
Aborted (core dumped)
``` 

### Expected Behavior

Puddletag should recognize that the file is too big, stop the process and inform the user about it.

### Steps To Reproduce

1. Open a FLAC-file
2. Import an image-file that is bigger than 16MB
3. experience crash

### Information about your system

Puddletag: 2.4.0
OS: Arch Linux
Python: 3.12.5
PyQt: 5.15.11
Qt: 5.15.14
Mutagen: 1.47.0
PyParsing: 3.1.2
ConfigObj: 5.0.8
Unidecode: 1.3.8
lxml: 5.3.0
pyacoustid: not installed
Levenshtein: not installed

**Comment by thefoster** [comment]
2 cents: why do you need such huge cover art?
I encountered issues with several players (beside getting slower) when the files embed images larger that 800x800 or 500kB, so i simply avoid that.

**Comment by Switch123456789** [comment]
I am preserving software & music from CD's, that's why I scan the cover-art with somewhat high dpi and store it lossless as PNG. It is a bit overkill but I want to preserve it as detailed as I can. Now I switched my routine to store it as jpg (99% compression-lvl) to work around the limitations.
